"""
Исходники статей раздела «Новости на немецком».

Каждая статья — список абзацев. Абзац — либо список предложений
(de, ru, g), либо фото: ('fig', имя_файла).

g — разметка подстрочника словами, а не индексами (индексы считает
tools/news/build.py по тому же WORD_RE, что у ридера):
    "Sonde"              — одно слово (первое вхождение);
    "Sonde#2"            — второе вхождение того же слова;
    "an der Erde"        — сочетание подряд идущих слов;
    "näherte+an"         — разорванная конструкция (отделяемая приставка);
    "die": ""            — не подписывать.
"""

ARTICLES = {}

# ════════════════════════════════════════════════════════════════════
#  1. Juice — гравитационный манёвр у Земли
# ════════════════════════════════════════════════════════════════════
ARTICLES['juice-erde-2026'] = [
    ('fig', 'earth'),
    [
        ("Die europäische Raumsonde Juice ist am 28. September 2026 erneut an der Erde vorbeigeflogen.",
         "Европейский зонд Juice 28 сентября 2026 года снова пролетел мимо Земли.",
         {"europäische": "европейский", "Raumsonde": "зонд", "ist+vorbeigeflogen": "пролетел мимо",
          "am": "", "September": "сентября", "erneut": "снова", "an der Erde": "Земли"}),
        ("Um 13:45 Uhr mitteleuropäischer Sommerzeit näherte sie sich unserem Planeten bis auf 8640 Kilometer.",
         "В 13:45 по центральноевропейскому летнему времени он приблизился к нашей планете на расстояние 8640 километров.",
         {"Um": "в", "Uhr": "часов", "mitteleuropäischer Sommerzeit": "по летнему времени ЦЕ",
          "näherte+sich": "приблизился", "unserem Planeten": "к нашей планете", "bis auf": "до",
          "Kilometer": "километров"}),
        ("Dabei flog sie über den Indischen Ozean.",
         "При этом он пролетал над Индийским океаном.",
         {"Dabei": "при этом", "flog": "летел", "über": "над", "Indischen Ozean": "Индийским океаном"}),
    ],
    [
        ("Das Manöver war kein Zufall, sondern ein sogenannter Swing-by.",
         "Манёвр не был случайностью — это был так называемый гравитационный манёвр.",
         {"Manöver": "манёвр", "war": "был", "kein Zufall": "не случайность", "sondern": "а",
          "sogenannter": "так называемый", "Swing-by": "гравитационный манёвр"}),
        ("Die Schwerkraft der Erde lenkte die Sonde um etwa 20 Grad ab und machte sie um 3,5 Kilometer pro Sekunde schneller.",
         "Притяжение Земли отклонило зонд примерно на 20 градусов и ускорило его на 3,5 километра в секунду.",
         {"Schwerkraft": "притяжение", "der Erde": "Земли", "lenkte+ab": "отклонило", "Sonde": "зонд",
          "um etwa": "примерно на", "Grad": "градусов", "machte+schneller": "сделало быстрее",
          "um#2": "на", "Kilometer": "километра", "pro Sekunde": "в секунду"}),
        ("Auf diese Weise spart die Mission wertvollen Treibstoff.",
         "Так миссия экономит драгоценное топливо.",
         {"Auf diese Weise": "таким образом", "spart": "экономит", "Mission": "миссия",
          "wertvollen": "ценное", "Treibstoff": "топливо"}),
    ],
    [
        ("»Der Vorbeiflug erforderte eine hochpräzise Navigation in Echtzeit«, sagte Angela Dietz, die bei der ESA für den Betrieb der Sonde verantwortlich ist.",
         "«Пролёт потребовал сверхточной навигации в реальном времени», — сказала Ангела Диц, которая отвечает в ЕКА за управление зондом.",
         {"Vorbeiflug": "пролёт", "erforderte": "потребовал", "hochpräzise": "сверхточную",
          "Navigation": "навигацию", "in Echtzeit": "в реальном времени", "sagte": "сказала",
          "die": "которая", "bei der ESA": "в ЕКА", "für": "за", "Betrieb": "управление",
          "der Sonde": "зондом", "verantwortlich ist": "отвечает"}),
        ("Von sechs geplanten Kurskorrekturen war nur eine einzige nötig.",
         "Из шести запланированных коррекций курса понадобилась лишь одна.",
         {"Von": "из", "sechs": "шести", "geplanten": "запланированных", "Kurskorrekturen": "коррекций курса",
          "war+nötig": "была нужна", "nur": "лишь", "eine einzige": "одна-единственная"}),
    ],
    [
        ("Während des Vorbeiflugs schalteten die Ingenieure mehrere Kameras und Messinstrumente ein.",
         "Во время пролёта инженеры включили несколько камер и измерительных приборов.",
         {"Während": "во время", "Vorbeiflugs": "пролёта", "schalteten+ein": "включили",
          "Ingenieure": "инженеры", "mehrere": "несколько", "Kameras": "камер",
          "Messinstrumente": "измерительных приборов"}),
        ("Eine Überwachungskamera fotografierte Afrika und Madagaskar, und in der Ecke des Bildes ist sogar der Mond als winziger grauer Punkt zu erkennen.",
         "Контрольная камера сфотографировала Африку и Мадагаскар, а в углу снимка можно различить даже Луну — крошечную серую точку.",
         {"Überwachungskamera": "контрольная камера", "fotografierte": "сфотографировала",
          "Afrika": "Африку", "Madagaskar": "Мадагаскар", "in der Ecke": "в углу",
          "des Bildes": "снимка", "ist+zu erkennen": "можно различить", "sogar": "даже",
          "Mond": "Луна", "als": "как", "winziger": "крошечная", "grauer": "серая", "Punkt": "точка"}),
    ],
    ('fig', 'madagascar'),
    [
        ("Die Navigationskamera hatte den Mond schon acht Stunden vor der größten Annäherung als schmale Sichel aufgenommen.",
         "Навигационная камера сняла Луну узким серпом ещё за восемь часов до максимального сближения.",
         {"Navigationskamera": "навигационная камера", "hatte+aufgenommen": "сняла", "den Mond": "Луну",
          "schon": "уже", "acht Stunden": "восемь часов", "vor": "до", "größten": "наибольшего",
          "Annäherung": "сближения", "als": "как", "schmale": "узкий", "Sichel": "серп"}),
    ],
    ('fig', 'moon'),
    [
        ("Für die Forscher ist ein solcher Vorbeiflug eine seltene Gelegenheit, die Instrumente unter bekannten Bedingungen zu testen.",
         "Для учёных такой пролёт — редкая возможность проверить приборы в известных условиях.",
         {"Für": "для", "Forscher": "учёных", "ist": "есть", "solcher": "такой", "Vorbeiflug": "пролёт",
          "seltene": "редкая", "Gelegenheit": "возможность", "Instrumente": "приборы",
          "unter bekannten Bedingungen": "в известных условиях", "zu testen": "проверить"}),
        ("Im Erdschatten musste Juice allein mit Batteriestrom auskommen.",
         "В тени Земли Juice пришлось обходиться одними аккумуляторами.",
         {"Im": "в", "Erdschatten": "тени Земли", "musste": "пришлось", "allein": "только",
          "mit Batteriestrom": "с питанием от батарей", "auskommen": "обходиться"}),
        ("Außerdem durchquerte die Sonde den Magnetschweif der Erde und maß dort Magnetfelder und geladene Teilchen.",
         "Кроме того, зонд пересёк магнитный хвост Земли и измерил там магнитные поля и заряженные частицы.",
         {"Außerdem": "кроме того", "durchquerte": "пересёк", "Sonde": "зонд",
          "Magnetschweif": "магнитный хвост", "der Erde": "Земли", "maß": "измерил", "dort": "там",
          "Magnetfelder": "магнитные поля", "geladene": "заряженные", "Teilchen": "частицы"}),
    ],
    ('fig', 'path'),
    [
        ("Juice ist seit April 2023 unterwegs.",
         "Juice находится в пути с апреля 2023 года.",
         {"ist+unterwegs": "в пути", "seit": "с", "April": "апреля"}),
        ("Im Januar 2029 soll die Sonde noch einmal an der Erde vorbeifliegen, im Juli 2031 erreicht sie dann den Jupiter.",
         "В январе 2029 года зонд должен ещё раз пролететь мимо Земли, а в июле 2031-го он достигнет Юпитера.",
         {"Im Januar": "в январе", "soll": "должен", "Sonde": "зонд", "noch einmal": "ещё раз",
          "an der Erde": "мимо Земли", "vorbeifliegen": "пролететь мимо", "im Juli": "в июле",
          "erreicht": "достигнет", "dann": "затем", "den Jupiter": "Юпитера"}),
        ("Dort soll sie die Eismonde Ganymed, Kallisto und Europa untersuchen, unter deren Oberfläche Ozeane vermutet werden.",
         "Там ему предстоит изучать ледяные спутники Ганимед, Каллисто и Европу, под поверхностью которых предполагают океаны.",
         {"Dort": "там", "soll": "должен", "Eismonde": "ледяные спутники", "Ganymed": "Ганимед",
          "Kallisto": "Каллисто", "Europa": "Европу", "untersuchen": "изучать", "unter": "под",
          "deren": "которых", "Oberfläche": "поверхностью", "Ozeane": "океаны",
          "vermutet werden": "предполагаются"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  2. Сатурн в противостоянии
# ════════════════════════════════════════════════════════════════════
ARTICLES['saturn-opposition-2026'] = [
    ('fig', 'cassini'),
    [
        ("Am 4. Oktober 2026 stand Saturn in Opposition zur Sonne.",
         "4 октября 2026 года Сатурн оказался в противостоянии с Солнцем.",
         {"Am": "", "Oktober": "октября", "stand": "стоял", "Saturn": "Сатурн",
          "in Opposition": "в противостоянии", "zur Sonne": "с Солнцем"}),
        ("Das bedeutet, dass die Erde genau zwischen der Sonne und dem Ringplaneten steht.",
         "Это значит, что Земля находится точно между Солнцем и окольцованной планетой.",
         {"Das": "это", "bedeutet": "значит", "dass": "что", "Erde": "Земля", "genau": "точно",
          "zwischen": "между", "der Sonne": "Солнцем", "dem Ringplaneten": "окольцованной планетой",
          "steht": "стоит"}),
        ("Saturn geht deshalb bei Sonnenuntergang auf, bei Sonnenaufgang unter und ist die ganze Nacht zu sehen.",
         "Поэтому Сатурн восходит на закате, заходит на рассвете и виден всю ночь.",
         {"Saturn": "Сатурн", "geht+auf": "восходит", "deshalb": "поэтому",
          "bei Sonnenuntergang": "на закате", "bei Sonnenaufgang": "на рассвете", "unter": "заходит",
          "ist+zu sehen": "виден", "die ganze Nacht": "всю ночь"}),
    ],
    ('fig', 'webb'),
    [
        ("In diesen Tagen ist uns Saturn so nah wie sonst im ganzen Jahr nicht.",
         "В эти дни Сатурн ближе к нам, чем в любое другое время года.",
         {"In diesen Tagen": "в эти дни", "ist": "", "uns": "к нам", "Saturn": "Сатурн",
          "so nah": "так близко", "wie": "как", "sonst": "в другое время", "im ganzen Jahr": "за весь год",
          "nicht": "не"}),
        ("Trotzdem trennen uns rund 1,26 Milliarden Kilometer von ihm.",
         "И всё же нас разделяют с ним около 1,26 миллиарда километров.",
         {"Trotzdem": "тем не менее", "trennen": "разделяют", "uns": "нас", "rund": "около",
          "Milliarden": "миллиарда", "Kilometer": "километров", "von ihm": "от него"}),
        ("Das Licht, das Saturn zurückwirft, ist bis zur Erde etwa 70 Minuten unterwegs.",
         "Свет, отражённый Сатурном, идёт до Земли около 70 минут.",
         {"Licht": "свет", "das": "который", "Saturn": "Сатурн", "zurückwirft": "отражает",
          "ist+unterwegs": "в пути", "bis zur Erde": "до Земли", "etwa": "около", "Minuten": "минут"}),
    ],
    [
        ("Mit einer Helligkeit von 0,3 Magnituden ist Saturn mit bloßem Auge leicht zu finden.",
         "При блеске 0,3 звёздной величины Сатурн легко найти невооружённым глазом.",
         {"Mit einer Helligkeit": "при яркости", "von": "в", "Magnituden": "звёздных величин",
          "ist+zu finden": "можно найти", "Saturn": "Сатурн", "mit bloßem Auge": "невооружённым глазом",
          "leicht": "легко"}),
        ("Er steht im Sternbild Walfisch, nahe der Grenze zu den Fischen, und leuchtet dort als hellster Punkt.",
         "Он находится в созвездии Кита, у границы с Рыбами, и светит там самой яркой точкой.",
         {"steht": "стоит", "im Sternbild": "в созвездии", "Walfisch": "Кит", "nahe": "вблизи",
          "der Grenze": "границы", "zu den Fischen": "с Рыбами", "leuchtet": "светит", "dort": "там",
          "als": "как", "hellster": "самая яркая", "Punkt": "точка"}),
        ("Am höchsten steht er gegen Mitternacht über dem Südhorizont.",
         "Выше всего он стоит около полуночи над южным горизонтом.",
         {"Am höchsten": "выше всего", "steht": "стоит", "gegen Mitternacht": "около полуночи",
          "über": "над", "dem Südhorizont": "южным горизонтом"}),
    ],
    [
        ("Wer ein kleines Teleskop besitzt, sollte jetzt unbedingt einen Blick auf die Ringe werfen.",
         "Тому, у кого есть небольшой телескоп, сейчас непременно стоит взглянуть на кольца.",
         {"Wer": "кто", "kleines": "небольшой", "Teleskop": "телескоп", "besitzt": "имеет",
          "sollte": "следует", "jetzt": "сейчас", "unbedingt": "непременно",
          "einen": "", "Blick+werfen": "бросить взгляд", "auf die Ringe": "на кольца"}),
        ("Im Jahr 2025 blickten wir genau auf ihre Kante, deshalb waren sie fast unsichtbar.",
         "В 2025 году мы смотрели точно на их ребро, поэтому они были почти невидимы.",
         {"Im Jahr": "в году", "blickten": "смотрели", "genau": "точно", "auf": "на",
          "ihre Kante": "их ребро", "deshalb": "поэтому", "waren": "были", "fast": "почти",
          "unsichtbar": "невидимы"}),
        ("Jetzt sind sie wieder um etwa sieben Grad geneigt und öffnen sich von Jahr zu Jahr weiter.",
         "Теперь они снова наклонены примерно на семь градусов и год от года раскрываются всё шире.",
         {"Jetzt": "теперь", "sind+geneigt": "наклонены", "wieder": "снова", "um etwa": "примерно на",
          "sieben Grad": "семь градусов", "öffnen sich": "раскрываются",
          "von Jahr zu Jahr": "год от года", "weiter": "дальше"}),
        ("Auch der größte Saturnmond Titan ist in einem kleinen Teleskop als Lichtpunkt neben dem Planeten zu erkennen.",
         "Крупнейший спутник Сатурна Титан тоже виден в небольшой телескоп как светлая точка рядом с планетой.",
         {"Auch": "тоже", "größte": "крупнейший", "Saturnmond": "спутник Сатурна", "Titan": "Титан",
          "ist+zu erkennen": "различим", "in einem kleinen Teleskop": "в небольшой телескоп",
          "als": "как", "Lichtpunkt": "светлая точка", "neben dem Planeten": "рядом с планетой"}),
    ],
    ('fig', 'hubble'),
    [
        ("Wie Saturn aus der Nähe aussieht, zeigen Bilder der beiden großen Weltraumteleskope.",
         "Как Сатурн выглядит вблизи, показывают снимки двух больших космических телескопов.",
         {"Wie": "как", "Saturn": "Сатурн", "aus der Nähe": "вблизи", "aussieht": "выглядит",
          "zeigen": "показывают", "Bilder": "снимки", "der beiden": "обоих", "großen": "больших",
          "Weltraumteleskope": "космических телескопов"}),
        ("Hubble fotografiert ihn im sichtbaren Licht, das James-Webb-Teleskop dagegen im Infrarot.",
         "«Хаббл» снимает его в видимом свете, а телескоп «Джеймс Уэбб» — в инфракрасном.",
         {"Hubble": "Хаббл", "fotografiert": "фотографирует", "ihn": "его",
          "im sichtbaren Licht": "в видимом свете", "James-Webb-Teleskop": "телескоп «Джеймс Уэбб»",
          "dagegen": "напротив", "im Infrarot": "в инфракрасном"}),
        ("Im Infrarot leuchten die eisigen Ringe besonders hell.",
         "В инфракрасном свете ледяные кольца сияют особенно ярко.",
         {"Im Infrarot": "в инфракрасном", "leuchten": "светятся", "eisigen": "ледяные",
          "Ringe": "кольца", "besonders": "особенно", "hell": "ярко"}),
    ],
    [
        ("Die nächste Opposition folgt Mitte Oktober 2027, dann sind die Ringe noch etwas weiter geöffnet.",
         "Следующее противостояние будет в середине октября 2027 года — тогда кольца раскроются ещё немного шире.",
         {"nächste": "следующее", "Opposition": "противостояние", "folgt": "последует",
          "Mitte Oktober": "в середине октября", "dann": "тогда", "sind+geöffnet": "раскрыты",
          "Ringe": "кольца", "noch etwas": "ещё немного", "weiter": "шире"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  3. Crew-13 — экипаж на МКС
# ════════════════════════════════════════════════════════════════════
ARTICLES['crew-13-iss-2026'] = [
    ('fig', 'launch'),
    [
        ("Am 1. Oktober 2026 ist die Mission Crew-13 vom Weltraumbahnhof Cape Canaveral in Florida gestartet.",
         "1 октября 2026 года с космодрома на мысе Канаверал во Флориде стартовала миссия Crew-13.",
         {"Am": "", "Oktober": "октября", "ist+gestartet": "стартовала", "Mission": "миссия",
          "vom Weltraumbahnhof": "с космодрома", "Cape Canaveral": "мыс Канаверал",
          "in Florida": "во Флориде"}),
        ("Eine Falcon-9-Rakete von SpaceX hob um 11:10 Uhr Ortszeit ab.",
         "Ракета Falcon 9 компании SpaceX стартовала в 11:10 по местному времени.",
         {"Rakete": "ракета", "von SpaceX": "компании SpaceX", "hob+ab": "взлетела", "um": "в",
          "Uhr": "часов", "Ortszeit": "местного времени"}),
        ("An Bord der Kapsel Crew Dragon »Grace« saßen vier Raumfahrer aus drei Ländern.",
         "На борту капсулы Crew Dragon «Grace» находились четверо космонавтов из трёх стран.",
         {"An Bord": "на борту", "der Kapsel": "капсулы", "saßen": "сидели", "vier": "четыре",
          "Raumfahrer": "космонавта", "aus drei Ländern": "из трёх стран"}),
    ],
    [
        ("Kommandantin ist die NASA-Astronautin Jessica Watkins, eine Geologin, die bereits zum zweiten Mal ins All fliegt.",
         "Командир — астронавт NASA Джессика Уоткинс, геолог, которая летит в космос уже во второй раз.",
         {"Kommandantin": "командир", "ist": "—", "NASA-Astronautin": "астронавт NASA",
          "Geologin": "геолог", "die#2": "которая", "bereits": "уже", "zum zweiten Mal": "во второй раз",
          "ins All": "в космос", "fliegt": "летит"}),
        ("Für Pilot Luke Delaney, den russischen Kosmonauten Sergei Teterjatnikow und den Kanadier Joshua Kutryk ist es der erste Raumflug.",
         "Для пилота Люка Делейни, российского космонавта Сергея Тетерятникова и канадца Джошуа Кутрика это первый космический полёт.",
         {"Für": "для", "Pilot": "пилота", "russischen": "российского", "Kosmonauten": "космонавта",
          "Kanadier": "канадца", "ist es": "это", "erste": "первый", "Raumflug": "космический полёт"}),
    ],
    ('fig', 'crew'),
    [
        ("Schon acht Stunden nach dem Start legte die Kapsel an der Internationalen Raumstation an.",
         "Уже через восемь часов после старта капсула пристыковалась к Международной космической станции.",
         {"Schon": "уже", "acht Stunden": "восемь часов", "nach dem Start": "после старта",
          "legte+an#2": "причалила", "Kapsel": "капсула", "an der": "к",
          "Internationalen Raumstation": "Международной космической станции"}),
        ("Für eine Besatzung der NASA ist das ein Rekord.",
         "Для экипажа NASA это рекорд.",
         {"Für": "для", "Besatzung": "экипажа", "ist das": "это", "Rekord": "рекорд"}),
        ("Die Kopplung erfolgte am Modul Harmony, während die Station über dem Nordostpazifik flog.",
         "Стыковка прошла к модулю Harmony, когда станция пролетала над северо-восточной частью Тихого океана.",
         {"Kopplung": "стыковка", "erfolgte": "произошла", "am Modul": "к модулю", "während": "пока",
          "Station": "станция", "über": "над", "dem Nordostpazifik": "северо-востоком Тихого океана",
          "flog": "летела"}),
    ],
    [
        ("Die vier Raumfahrer bleiben etwa sechs Monate an Bord.",
         "Четверо космонавтов пробудут на борту около шести месяцев.",
         {"vier": "четыре", "Raumfahrer": "космонавта", "bleiben": "останутся", "etwa": "около",
          "sechs Monate": "шесть месяцев", "an Bord": "на борту"}),
        ("Sie sollen die Station warten, mehrere Außeneinsätze absolvieren und Frachtschiffe in Empfang nehmen.",
         "Им предстоит обслуживать станцию, совершить несколько выходов в открытый космос и принимать грузовые корабли.",
         {"sollen": "должны", "Station": "станцию", "warten": "обслуживать", "mehrere": "несколько",
          "Außeneinsätze": "выходов в космос", "absolvieren": "выполнить",
          "Frachtschiffe": "грузовые корабли", "in Empfang nehmen": "принимать"}),
        ("Auf dem Programm stehen außerdem zahlreiche Experimente, etwa mit Stammzellen, die bei der Behandlung von Herzkrankheiten und Parkinson helfen könnten.",
         "В программе также многочисленные эксперименты — например, со стволовыми клетками, которые могли бы помочь в лечении болезней сердца и Паркинсона.",
         {"Auf dem Programm": "в программе", "stehen": "стоят", "außerdem": "кроме того",
          "zahlreiche": "многочисленные", "Experimente": "эксперименты", "etwa": "например",
          "mit Stammzellen": "со стволовыми клетками", "die": "которые",
          "bei der Behandlung": "при лечении", "von Herzkrankheiten": "болезней сердца",
          "Parkinson": "Паркинсона", "helfen": "помочь", "könnten": "могли бы"}),
        ("Andere Versuche beschäftigen sich mit dem Anbau von Pflanzen im All.",
         "Другие опыты посвящены выращиванию растений в космосе.",
         {"Andere": "другие", "Versuche": "опыты", "beschäftigen sich": "занимаются",
          "mit dem Anbau": "выращиванием", "von Pflanzen": "растений", "im All": "в космосе"}),
    ],
    ('fig', 'sunset'),
    [
        ("Für Joshua Kutryk ist die Mission auch privat etwas Besonderes, denn seine Frau erwartet in einigen Wochen das dritte Kind.",
         "Для Джошуа Кутрика миссия особенная и в личном плане: через несколько недель его жена ждёт третьего ребёнка.",
         {"Für": "для", "ist": "", "Mission": "миссия", "auch": "и", "privat": "в личном плане",
          "etwas Besonderes": "нечто особенное", "denn": "ведь", "seine Frau": "его жена",
          "erwartet": "ждёт", "in einigen Wochen": "через несколько недель", "dritte": "третьего",
          "Kind": "ребёнка"}),
        ("Die Geburt wird er also aus dem Weltraum miterleben.",
         "Значит, рождение ребёнка он переживёт из космоса.",
         {"Geburt": "рождение", "wird+miterleben": "переживёт вместе", "also": "значит",
          "aus dem Weltraum": "из космоса"}),
        ("Die bisherige Besatzung Crew-12 soll die Station frühestens am 7. Oktober verlassen.",
         "Предыдущий экипаж Crew-12 должен покинуть станцию не раньше 7 октября.",
         {"bisherige": "прежний", "Besatzung": "экипаж", "soll": "должен", "Station": "станцию",
          "frühestens": "не раньше", "am": "", "Oktober": "октября", "verlassen": "покинуть"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  4. Экономика — правительство повысило прогноз роста
# ════════════════════════════════════════════════════════════════════
ARTICLES['wirtschaft-prognose-2026'] = [
    ('fig', 'hafen'),
    [
        ("Die Bundesregierung ist für die deutsche Wirtschaft deutlich optimistischer geworden.",
         "Федеральное правительство стало заметно оптимистичнее смотреть на экономику Германии.",
         {"Bundesregierung": "федеральное правительство", "ist+geworden": "стало", "für": "в отношении",
          "deutsche": "немецкой", "Wirtschaft": "экономики", "deutlich": "заметно",
          "optimistischer": "оптимистичнее"}),
        ("Nach Informationen der Nachrichtenagentur Reuters rechnet sie für das Jahr 2026 jetzt mit einem Wachstum von 1,3 Prozent.",
         "По данным агентства Reuters, теперь оно рассчитывает на рост в 2026 году на 1,3 процента.",
         {"Nach Informationen": "по информации", "der Nachrichtenagentur": "информагентства",
          "rechnet+mit": "рассчитывает на", "für das Jahr": "на год", "jetzt": "теперь",
          "einem": "", "Wachstum": "рост", "von": "в", "Prozent": "процента"}),
        ("Im Frühjahr hatte sie nur 0,5 Prozent erwartet.",
         "Весной оно ожидало лишь 0,5 процента.",
         {"Im Frühjahr": "весной", "hatte+erwartet": "ожидало", "nur": "лишь", "Prozent": "процента"}),
    ],
    [
        ("Auch für 2027 wurde die Prognose angehoben: von 0,9 auf 1,1 Prozent.",
         "Прогноз на 2027 год тоже повысили: с 0,9 до 1,1 процента.",
         {"Auch": "тоже", "für": "на", "wurde+angehoben": "был повышен", "Prognose": "прогноз",
          "von": "с", "auf": "до", "Prozent": "процента"}),
        ("Für 2028 erwartet die Regierung ein Plus von 0,6 Prozent.",
         "На 2028 год правительство ожидает прирост в 0,6 процента.",
         {"Für": "на", "erwartet": "ожидает", "Regierung": "правительство", "Plus": "прирост",
          "von": "в", "Prozent": "процента"}),
        ("Offiziell will sie die neuen Zahlen am 8. Oktober vorstellen.",
         "Официально новые цифры оно собирается представить 8 октября.",
         {"Offiziell": "официально", "will": "хочет", "neuen": "новые", "Zahlen": "цифры",
          "am": "", "Oktober": "октября", "vorstellen": "представить"}),
    ],
    ('fig', 'bruecke'),
    [
        ("Der wichtigste Grund für den Aufschwung sind die Investitionen des Staates.",
         "Главная причина подъёма — государственные инвестиции.",
         {"wichtigste": "важнейшая", "Grund": "причина", "für den Aufschwung": "подъёма",
          "sind": "—", "Investitionen": "инвестиции", "des Staates": "государства"}),
        ("Mit neuen Schulden finanziert der Bund Straßen, Brücken und Schienen, außerdem gibt er mehr Geld für die Bundeswehr aus.",
         "На новые долги федерация финансирует дороги, мосты и железные дороги, а кроме того тратит больше денег на бундесвер.",
         {"Mit neuen Schulden": "на новые долги", "finanziert": "финансирует", "Bund": "федерация",
          "Straßen": "дороги", "Brücken": "мосты", "Schienen": "рельсы", "außerdem": "кроме того",
          "gibt+aus": "тратит", "mehr Geld": "больше денег", "für die Bundeswehr": "на бундесвер"}),
        ("Davon profitieren vor allem die Bauwirtschaft und die Industrie.",
         "Выигрывают от этого прежде всего строительная отрасль и промышленность.",
         {"Davon": "от этого", "profitieren": "выигрывают", "vor allem": "прежде всего",
          "Bauwirtschaft": "строительная отрасль", "Industrie": "промышленность"}),
    ],
    [
        ("Bei den Exporten rechnet die Regierung in diesem Jahr mit einem Plus von 3,7 Prozent.",
         "По экспорту правительство рассчитывает в этом году на прирост в 3,7 процента.",
         {"Bei den Exporten": "по экспорту", "rechnet+mit": "рассчитывает на", "Regierung": "правительство",
          "in diesem Jahr": "в этом году", "einem": "", "Plus": "прирост", "von": "в", "Prozent": "процента"}),
        ("Dabei bleibt die Lage schwierig: Die Zölle der USA verunsichern viele Unternehmen, und der Konflikt im Nahen Osten hat das Öl teurer gemacht.",
         "При этом ситуация остаётся сложной: пошлины США тревожат многие компании, а конфликт на Ближнем Востоке сделал нефть дороже.",
         {"Dabei": "при этом", "bleibt": "остаётся", "Lage": "ситуация", "schwierig": "сложной",
          "Zölle": "пошлины", "der USA": "США", "verunsichern": "тревожат", "viele": "многие",
          "Unternehmen": "компании", "Konflikt": "конфликт", "im Nahen Osten": "на Ближнем Востоке",
          "hat+gemacht": "сделал", "Öl": "нефть", "teurer": "дороже"}),
    ],
    [
        ("Die Verbraucher spüren das vor allem an den Preisen.",
         "Потребители ощущают это прежде всего по ценам.",
         {"Verbraucher": "потребители", "spüren": "ощущают", "das": "это", "vor allem": "прежде всего",
          "an den Preisen": "по ценам"}),
        ("Benzin und Diesel kosten deutlich mehr als noch vor einem Jahr.",
         "Бензин и дизель стоят заметно больше, чем год назад.",
         {"Benzin": "бензин", "Diesel": "дизель", "kosten": "стоят", "deutlich": "заметно",
          "mehr als": "больше, чем", "noch": "ещё", "vor einem Jahr": "год назад"}),
        ("Die Inflation soll 2026 bei 2,7 Prozent liegen und 2027 sogar auf 3,0 Prozent steigen.",
         "Инфляция в 2026 году должна составить 2,7 процента, а в 2027-м даже вырасти до 3,0 процента.",
         {"Inflation": "инфляция", "soll": "должна", "bei": "на уровне", "Prozent": "процента",
          "liegen": "находиться", "sogar": "даже", "auf": "до", "Prozent#2": "процента",
          "steigen": "вырасти"}),
        ("Deshalb kaufen viele Menschen vorsichtig ein: Der private Konsum wächst in diesem Jahr voraussichtlich nur um 0,8 Prozent.",
         "Поэтому многие покупают осторожно: частное потребление в этом году, по прогнозу, вырастет лишь на 0,8 процента.",
         {"Deshalb": "поэтому", "kaufen+ein": "делают покупки", "viele Menschen": "многие люди",
          "vorsichtig": "осторожно", "private": "частное", "Konsum": "потребление", "wächst": "растёт",
          "in diesem Jahr": "в этом году", "voraussichtlich": "предположительно", "nur": "лишь",
          "um": "на", "Prozent": "процента"}),
    ],
    ('fig', 'bundesbank'),
    [
        ("Auch die Bundesbank ist zuversichtlicher geworden.",
         "Бундесбанк тоже стал смотреть в будущее увереннее.",
         {"Auch": "тоже", "Bundesbank": "Бундесбанк", "ist+geworden": "стал",
          "zuversichtlicher": "увереннее"}),
        ("Ihr Präsident Joachim Nagel sagte, die Wirtschaft könne in diesem Jahr um etwa ein Prozent wachsen.",
         "Его президент Йоахим Нагель сказал, что экономика в этом году может вырасти примерно на один процент.",
         {"Ihr": "его", "Präsident": "президент", "sagte": "сказал", "Wirtschaft": "экономика",
          "könne": "может (по его словам)", "in diesem Jahr": "в этом году", "um etwa": "примерно на",
          "ein Prozent": "один процент", "wachsen": "вырасти"}),
        ("Nach drei Jahren ohne Wachstum wäre das ein kleines, aber wichtiges Signal.",
         "После трёх лет без роста это был бы небольшой, но важный сигнал.",
         {"Nach drei Jahren": "после трёх лет", "ohne Wachstum": "без роста", "wäre": "был бы",
          "das": "это", "kleines": "небольшой", "aber": "но", "wichtiges": "важный", "Signal": "сигнал"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  5. События — День немецкого единства в Бремене
# ════════════════════════════════════════════════════════════════════
ARTICLES['einheitsfeier-bremen-2026'] = [
    ('fig', 'markt'),
    [
        ("Drei Tage lang hat Bremen den Tag der Deutschen Einheit gefeiert.",
         "Три дня Бремен праздновал День немецкого единства.",
         {"Drei Tage lang": "три дня", "hat+gefeiert": "праздновал", "Bremen": "Бремен",
          "Tag der Deutschen Einheit": "День немецкого единства"}),
        ("Vom 2. bis zum 4. Oktober kamen rund 550.000 Besucher in die Stadt an der Weser.",
         "Со 2 по 4 октября в город на Везере приехали около 550 000 гостей.",
         {"Vom": "с", "bis zum": "по", "Oktober": "октября", "kamen": "пришли", "rund": "около",
          "Besucher": "посетителей", "in die Stadt": "в город", "an der Weser": "на Везере"}),
        ("Erwartet hatte man nur etwa 450.000 Gäste.",
         "Ожидали всего около 450 000 гостей.",
         {"Erwartet+hatte": "ожидали", "man": "", "nur": "лишь", "etwa": "около", "Gäste": "гостей"}),
    ],
    [
        ("Die zentrale Feier findet jedes Jahr in dem Bundesland statt, das gerade den Vorsitz im Bundesrat hat.",
         "Главный праздник каждый год проходит в той федеральной земле, которая в этот момент председательствует в бундесрате.",
         {"zentrale": "центральный", "Feier": "праздник", "findet+statt": "проходит",
          "jedes Jahr": "каждый год", "in dem Bundesland": "в федеральной земле", "das": "которая",
          "gerade": "как раз", "den Vorsitz": "председательство", "im Bundesrat": "в бундесрате", "hat": "имеет"}),
        ("In diesem Jahr war das Bremen – nach 1994 und 2010 schon zum dritten Mal.",
         "В этом году это был Бремен — уже в третий раз после 1994 и 2010 годов.",
         {"In diesem Jahr": "в этом году", "war": "был", "das": "это", "Bremen": "Бремен",
          "nach": "после", "schon": "уже", "zum dritten Mal": "в третий раз"}),
        ("Das Motto lautete »Viele Stärken – ein Land«.",
         "Девиз звучал так: «Много сильных сторон — одна страна».",
         {"Motto": "девиз", "lautete": "гласил", "Viele": "много", "Stärken": "сильных сторон",
          "ein Land": "одна страна"}),
    ],
    ('fig', 'glocke'),
    [
        ("Am 3. Oktober begann der offizielle Teil mit einem Gottesdienst im Bremer Dom.",
         "3 октября официальная часть началась с богослужения в Бременском соборе.",
         {"Am": "", "Oktober": "октября", "begann": "началась", "offizielle": "официальная",
          "Teil": "часть", "mit einem Gottesdienst": "с богослужения", "im Bremer Dom": "в Бременском соборе"}),
        ("Danach folgte ein Festakt im Konzerthaus »Die Glocke«.",
         "Затем последовало торжественное собрание в концертном зале «Колокол».",
         {"Danach": "затем", "folgte": "последовал", "Festakt": "торжественный акт",
          "im Konzerthaus": "в концертном зале", "Die Glocke": "«Колокол»"}),
        ("Dort hielt Bundespräsident Frank-Walter Steinmeier eine Rede.",
         "Там выступил с речью федеральный президент Франк-Вальтер Штайнмайер.",
         {"Dort": "там", "hielt+Rede": "произнёс речь", "Bundespräsident": "федеральный президент",
          "eine": ""}),
    ],
    [
        ("Er erinnerte an die Friedliche Revolution von 1989 und an das Glück der Wiedervereinigung.",
         "Он напомнил о Мирной революции 1989 года и о счастье воссоединения.",
         {"erinnerte+an": "напомнил о", "Friedliche Revolution": "Мирную революцию", "von": "",
          "an#2": "о", "Glück": "счастье", "der Wiedervereinigung": "воссоединения"}),
        ("Gleichzeitig warnte er vor Extremismus und Spaltung: Die Demagogie extremistischer Kräfte gefährde nicht nur Freiheit und Demokratie, sondern auch die Einheit.",
         "Вместе с тем он предостерёг от экстремизма и раскола: демагогия экстремистских сил, по его словам, угрожает не только свободе и демократии, но и единству.",
         {"Gleichzeitig": "одновременно", "warnte+vor": "предостерёг от", "Extremismus": "экстремизма",
          "Spaltung": "раскола", "Demagogie": "демагогия", "extremistischer Kräfte": "экстремистских сил",
          "gefährde": "угрожает (по его словам)", "nicht nur": "не только", "Freiheit": "свободе",
          "Demokratie": "демократии", "sondern auch": "но и", "Einheit": "единству"}),
        ("Am Ende rief er: »Unser Deutschland ist ein gutes Land! Sorgen wir dafür, dass es so bleibt!«",
         "В конце он призвал: «Наша Германия — хорошая страна! Позаботимся о том, чтобы так и оставалось!»",
         {"Am Ende": "в конце", "rief": "воскликнул", "Unser": "наша", "ist": "—", "gutes Land": "хорошая страна",
          "Sorgen+dafür": "позаботимся о том", "dass": "чтобы", "es": "", "so": "так", "bleibt": "оставалось"}),
    ],
    ('fig', 'musikanten'),
    [
        ("In der ganzen Innenstadt fand ein großes Bürgerfest statt.",
         "По всему центру города прошёл большой народный праздник.",
         {"In der ganzen Innenstadt": "по всему центру", "fand+statt": "прошёл", "großes": "большой",
          "Bürgerfest": "народный праздник"}),
        ("Auf mehreren Bühnen gab es Konzerte, Theater und Lesungen, unter anderem mit den Fantastischen Vier.",
         "На нескольких сценах шли концерты, спектакли и чтения — среди прочих выступили Die Fantastischen Vier.",
         {"Auf mehreren Bühnen": "на нескольких сценах", "gab es": "были", "Konzerte": "концерты",
          "Theater": "театр", "Lesungen": "чтения", "unter anderem": "среди прочего",
          "mit den Fantastischen Vier": "с группой Die Fantastischen Vier"}),
        ("Auf der Ländermeile am Osterdeich stellten sich alle 16 Bundesländer vor.",
         "На «Миле земель» у дамбы Остердайх представились все 16 федеральных земель.",
         {"Auf der Ländermeile": "на «Миле земель»", "am Osterdeich": "у Остердайха",
          "stellten+vor": "представились", "sich": "", "alle": "все", "Bundesländer": "федеральные земли"}),
        ("Busse und Bahnen in der ganzen Region waren kostenlos.",
         "Автобусы и поезда во всём регионе были бесплатными.",
         {"Busse": "автобусы", "Bahnen": "поезда", "in der ganzen Region": "во всём регионе",
          "waren": "были", "kostenlos": "бесплатными"}),
    ],
    ('fig', 'schlachte'),
    [
        ("Rund 4000 Polizistinnen und Polizisten sorgten für Sicherheit.",
         "Около 4000 полицейских обеспечивали безопасность.",
         {"Rund": "около", "Polizistinnen und Polizisten": "полицейские", "sorgten+für": "обеспечивали",
          "Sicherheit": "безопасность"}),
        ("Bis auf einzelne Zusammenstöße bei einer Demonstration blieb es friedlich.",
         "Если не считать отдельных стычек на одной демонстрации, всё прошло мирно.",
         {"Bis auf": "за исключением", "einzelne": "отдельных", "Zusammenstöße": "столкновений",
          "bei einer Demonstration": "на демонстрации", "blieb": "оставалось", "es": "", "friedlich": "мирно"}),
        ("Bürgermeister Andreas Bovenschulte sprach von drei wunderbaren Tagen.",
         "Бургомистр Андреас Бовеншульте говорил о трёх замечательных днях.",
         {"Bürgermeister": "бургомистр", "sprach+von": "говорил о", "drei": "трёх",
          "wunderbaren": "замечательных", "Tagen": "днях"}),
        ("Im nächsten Jahr ist Düsseldorf an der Reihe.",
         "В следующем году очередь Дюссельдорфа.",
         {"Im nächsten Jahr": "в следующем году", "ist+an der Reihe": "очередь (за)",
          "Düsseldorf": "Дюссельдорф"}),
    ],
]
