"""
Исходники статей раздела «Новости на немецком».

Каждая статья — список абзацев. Абзац — либо список предложений
(de, ru, g), либо фото: ('fig', имя_файла).

g — разметка подстрочника словами, а не индексами (индексы считает
tools/news/build.py по тому же WORD_RE, что у ридера):
    "Sonde"              — одно слово (первое вхождение);
    "Sonde#2"            — второе вхождение того же слова;
    "an der Erde"        — сочетание подряд идущих слов;
    "näherte+an"         — разорванная конструкция (отделяемая приставка);
    "die": ""            — не подписывать.
"""

ARTICLES = {}

# ════════════════════════════════════════════════════════════════════
#  1. Juice — гравитационный манёвр у Земли
# ════════════════════════════════════════════════════════════════════
ARTICLES['juice-erde-2026'] = [
    ('fig', 'earth'),
    [
        ("Die europäische Raumsonde Juice ist am 28. September 2026 erneut an der Erde vorbeigeflogen.",
         "Европейский зонд Juice 28 сентября 2026 года снова пролетел мимо Земли.",
         {"europäische": "европейский", "Raumsonde": "зонд", "ist+vorbeigeflogen": "пролетел мимо",
          "am": "", "September": "сентября", "erneut": "снова", "an der Erde": "Земли"}),
        ("Um 13:45 Uhr mitteleuropäischer Sommerzeit näherte sie sich unserem Planeten bis auf 8640 Kilometer.",
         "В 13:45 по центральноевропейскому летнему времени он приблизился к нашей планете на расстояние 8640 километров.",
         {"Um": "в", "Uhr": "часов", "mitteleuropäischer Sommerzeit": "по летнему времени ЦЕ",
          "näherte+sich": "приблизился", "unserem Planeten": "к нашей планете", "bis auf": "до",
          "Kilometer": "километров"}),
        ("Dabei flog sie über den Indischen Ozean.",
         "При этом он пролетал над Индийским океаном.",
         {"Dabei": "при этом", "flog": "летел", "über": "над", "Indischen Ozean": "Индийским океаном"}),
    ],
    [
        ("Das Manöver war kein Zufall, sondern ein sogenannter Swing-by.",
         "Манёвр не был случайностью — это был так называемый гравитационный манёвр.",
         {"Manöver": "манёвр", "war": "был", "kein Zufall": "не случайность", "sondern": "а",
          "sogenannter": "так называемый", "Swing-by": "гравитационный манёвр"}),
        ("Die Schwerkraft der Erde lenkte die Sonde um etwa 20 Grad ab und machte sie um 3,5 Kilometer pro Sekunde schneller.",
         "Притяжение Земли отклонило зонд примерно на 20 градусов и ускорило его на 3,5 километра в секунду.",
         {"Schwerkraft": "притяжение", "der Erde": "Земли", "lenkte+ab": "отклонило", "Sonde": "зонд",
          "um etwa": "примерно на", "Grad": "градусов", "machte+schneller": "сделало быстрее",
          "um#2": "на", "Kilometer": "километра", "pro Sekunde": "в секунду"}),
        ("Auf diese Weise spart die Mission wertvollen Treibstoff.",
         "Так миссия экономит драгоценное топливо.",
         {"Auf diese Weise": "таким образом", "spart": "экономит", "Mission": "миссия",
          "wertvollen": "ценное", "Treibstoff": "топливо"}),
    ],
    [
        ("»Der Vorbeiflug erforderte eine hochpräzise Navigation in Echtzeit«, sagte Angela Dietz, die bei der ESA für den Betrieb der Sonde verantwortlich ist.",
         "«Пролёт потребовал сверхточной навигации в реальном времени», — сказала Ангела Диц, которая отвечает в ЕКА за управление зондом.",
         {"Vorbeiflug": "пролёт", "erforderte": "потребовал", "hochpräzise": "сверхточную",
          "Navigation": "навигацию", "in Echtzeit": "в реальном времени", "sagte": "сказала",
          "die": "которая", "bei der ESA": "в ЕКА", "für": "за", "Betrieb": "управление",
          "der Sonde": "зондом", "verantwortlich ist": "отвечает"}),
        ("Von sechs geplanten Kurskorrekturen war nur eine einzige nötig.",
         "Из шести запланированных коррекций курса понадобилась лишь одна.",
         {"Von": "из", "sechs": "шести", "geplanten": "запланированных", "Kurskorrekturen": "коррекций курса",
          "war+nötig": "была нужна", "nur": "лишь", "eine einzige": "одна-единственная"}),
    ],
    [
        ("Während des Vorbeiflugs schalteten die Ingenieure mehrere Kameras und Messinstrumente ein.",
         "Во время пролёта инженеры включили несколько камер и измерительных приборов.",
         {"Während": "во время", "Vorbeiflugs": "пролёта", "schalteten+ein": "включили",
          "Ingenieure": "инженеры", "mehrere": "несколько", "Kameras": "камер",
          "Messinstrumente": "измерительных приборов"}),
        ("Eine Überwachungskamera fotografierte Afrika und Madagaskar, und in der Ecke des Bildes ist sogar der Mond als winziger grauer Punkt zu erkennen.",
         "Контрольная камера сфотографировала Африку и Мадагаскар, а в углу снимка можно различить даже Луну — крошечную серую точку.",
         {"Überwachungskamera": "контрольная камера", "fotografierte": "сфотографировала",
          "Afrika": "Африку", "Madagaskar": "Мадагаскар", "in der Ecke": "в углу",
          "des Bildes": "снимка", "ist+zu erkennen": "можно различить", "sogar": "даже",
          "Mond": "Луна", "als": "как", "winziger": "крошечная", "grauer": "серая", "Punkt": "точка"}),
    ],
    ('fig', 'madagascar'),
    [
        ("Die Navigationskamera hatte den Mond schon acht Stunden vor der größten Annäherung als schmale Sichel aufgenommen.",
         "Навигационная камера сняла Луну узким серпом ещё за восемь часов до максимального сближения.",
         {"Navigationskamera": "навигационная камера", "hatte+aufgenommen": "сняла", "den Mond": "Луну",
          "schon": "уже", "acht Stunden": "восемь часов", "vor": "до", "größten": "наибольшего",
          "Annäherung": "сближения", "als": "как", "schmale": "узкий", "Sichel": "серп"}),
    ],
    ('fig', 'moon'),
    [
        ("Für die Forscher ist ein solcher Vorbeiflug eine seltene Gelegenheit, die Instrumente unter bekannten Bedingungen zu testen.",
         "Для учёных такой пролёт — редкая возможность проверить приборы в известных условиях.",
         {"Für": "для", "Forscher": "учёных", "ist": "есть", "solcher": "такой", "Vorbeiflug": "пролёт",
          "seltene": "редкая", "Gelegenheit": "возможность", "Instrumente": "приборы",
          "unter bekannten Bedingungen": "в известных условиях", "zu testen": "проверить"}),
        ("Im Erdschatten musste Juice allein mit Batteriestrom auskommen.",
         "В тени Земли Juice пришлось обходиться одними аккумуляторами.",
         {"Im": "в", "Erdschatten": "тени Земли", "musste": "пришлось", "allein": "только",
          "mit Batteriestrom": "с питанием от батарей", "auskommen": "обходиться"}),
        ("Außerdem durchquerte die Sonde den Magnetschweif der Erde und maß dort Magnetfelder und geladene Teilchen.",
         "Кроме того, зонд пересёк магнитный хвост Земли и измерил там магнитные поля и заряженные частицы.",
         {"Außerdem": "кроме того", "durchquerte": "пересёк", "Sonde": "зонд",
          "Magnetschweif": "магнитный хвост", "der Erde": "Земли", "maß": "измерил", "dort": "там",
          "Magnetfelder": "магнитные поля", "geladene": "заряженные", "Teilchen": "частицы"}),
    ],
    ('fig', 'path'),
    [
        ("Juice ist seit April 2023 unterwegs.",
         "Juice находится в пути с апреля 2023 года.",
         {"ist+unterwegs": "в пути", "seit": "с", "April": "апреля"}),
        ("Im Januar 2029 soll die Sonde noch einmal an der Erde vorbeifliegen, im Juli 2031 erreicht sie dann den Jupiter.",
         "В январе 2029 года зонд должен ещё раз пролететь мимо Земли, а в июле 2031-го он достигнет Юпитера.",
         {"Im Januar": "в январе", "soll": "должен", "Sonde": "зонд", "noch einmal": "ещё раз",
          "an der Erde": "мимо Земли", "vorbeifliegen": "пролететь мимо", "im Juli": "в июле",
          "erreicht": "достигнет", "dann": "затем", "den Jupiter": "Юпитера"}),
        ("Dort soll sie die Eismonde Ganymed, Kallisto und Europa untersuchen, unter deren Oberfläche Ozeane vermutet werden.",
         "Там ему предстоит изучать ледяные спутники Ганимед, Каллисто и Европу, под поверхностью которых предполагают океаны.",
         {"Dort": "там", "soll": "должен", "Eismonde": "ледяные спутники", "Ganymed": "Ганимед",
          "Kallisto": "Каллисто", "Europa": "Европу", "untersuchen": "изучать", "unter": "под",
          "deren": "которых", "Oberfläche": "поверхностью", "Ozeane": "океаны",
          "vermutet werden": "предполагаются"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  2. Сатурн в противостоянии
# ════════════════════════════════════════════════════════════════════
ARTICLES['saturn-opposition-2026'] = [
    ('fig', 'cassini'),
    [
        ("Am 4. Oktober 2026 stand Saturn in Opposition zur Sonne.",
         "4 октября 2026 года Сатурн оказался в противостоянии с Солнцем.",
         {"Am": "", "Oktober": "октября", "stand": "стоял", "Saturn": "Сатурн",
          "in Opposition": "в противостоянии", "zur Sonne": "с Солнцем"}),
        ("Das bedeutet, dass die Erde genau zwischen der Sonne und dem Ringplaneten steht.",
         "Это значит, что Земля находится точно между Солнцем и окольцованной планетой.",
         {"Das": "это", "bedeutet": "значит", "dass": "что", "Erde": "Земля", "genau": "точно",
          "zwischen": "между", "der Sonne": "Солнцем", "dem Ringplaneten": "окольцованной планетой",
          "steht": "стоит"}),
        ("Saturn geht deshalb bei Sonnenuntergang auf, bei Sonnenaufgang unter und ist die ganze Nacht zu sehen.",
         "Поэтому Сатурн восходит на закате, заходит на рассвете и виден всю ночь.",
         {"Saturn": "Сатурн", "geht+auf": "восходит", "deshalb": "поэтому",
          "bei Sonnenuntergang": "на закате", "bei Sonnenaufgang": "на рассвете", "unter": "заходит",
          "ist+zu sehen": "виден", "die ganze Nacht": "всю ночь"}),
    ],
    ('fig', 'webb'),
    [
        ("In diesen Tagen ist uns Saturn so nah wie sonst im ganzen Jahr nicht.",
         "В эти дни Сатурн ближе к нам, чем в любое другое время года.",
         {"In diesen Tagen": "в эти дни", "ist": "", "uns": "к нам", "Saturn": "Сатурн",
          "so nah": "так близко", "wie": "как", "sonst": "в другое время", "im ganzen Jahr": "за весь год",
          "nicht": "не"}),
        ("Trotzdem trennen uns rund 1,26 Milliarden Kilometer von ihm.",
         "И всё же нас разделяют с ним около 1,26 миллиарда километров.",
         {"Trotzdem": "тем не менее", "trennen": "разделяют", "uns": "нас", "rund": "около",
          "Milliarden": "миллиарда", "Kilometer": "километров", "von ihm": "от него"}),
        ("Das Licht, das Saturn zurückwirft, ist bis zur Erde etwa 70 Minuten unterwegs.",
         "Свет, отражённый Сатурном, идёт до Земли около 70 минут.",
         {"Licht": "свет", "das": "который", "Saturn": "Сатурн", "zurückwirft": "отражает",
          "ist+unterwegs": "в пути", "bis zur Erde": "до Земли", "etwa": "около", "Minuten": "минут"}),
    ],
    [
        ("Mit einer Helligkeit von 0,3 Magnituden ist Saturn mit bloßem Auge leicht zu finden.",
         "При блеске 0,3 звёздной величины Сатурн легко найти невооружённым глазом.",
         {"Mit einer Helligkeit": "при яркости", "von": "в", "Magnituden": "звёздных величин",
          "ist+zu finden": "можно найти", "Saturn": "Сатурн", "mit bloßem Auge": "невооружённым глазом",
          "leicht": "легко"}),
        ("Er steht im Sternbild Walfisch, nahe der Grenze zu den Fischen, und leuchtet dort als hellster Punkt.",
         "Он находится в созвездии Кита, у границы с Рыбами, и светит там самой яркой точкой.",
         {"steht": "стоит", "im Sternbild": "в созвездии", "Walfisch": "Кит", "nahe": "вблизи",
          "der Grenze": "границы", "zu den Fischen": "с Рыбами", "leuchtet": "светит", "dort": "там",
          "als": "как", "hellster": "самая яркая", "Punkt": "точка"}),
        ("Am höchsten steht er gegen Mitternacht über dem Südhorizont.",
         "Выше всего он стоит около полуночи над южным горизонтом.",
         {"Am höchsten": "выше всего", "steht": "стоит", "gegen Mitternacht": "около полуночи",
          "über": "над", "dem Südhorizont": "южным горизонтом"}),
    ],
    [
        ("Wer ein kleines Teleskop besitzt, sollte jetzt unbedingt einen Blick auf die Ringe werfen.",
         "Тому, у кого есть небольшой телескоп, сейчас непременно стоит взглянуть на кольца.",
         {"Wer": "кто", "kleines": "небольшой", "Teleskop": "телескоп", "besitzt": "имеет",
          "sollte": "следует", "jetzt": "сейчас", "unbedingt": "непременно",
          "einen": "", "Blick+werfen": "бросить взгляд", "auf die Ringe": "на кольца"}),
        ("Im Jahr 2025 blickten wir genau auf ihre Kante, deshalb waren sie fast unsichtbar.",
         "В 2025 году мы смотрели точно на их ребро, поэтому они были почти невидимы.",
         {"Im Jahr": "в году", "blickten": "смотрели", "genau": "точно", "auf": "на",
          "ihre Kante": "их ребро", "deshalb": "поэтому", "waren": "были", "fast": "почти",
          "unsichtbar": "невидимы"}),
        ("Jetzt sind sie wieder um etwa sieben Grad geneigt und öffnen sich von Jahr zu Jahr weiter.",
         "Теперь они снова наклонены примерно на семь градусов и год от года раскрываются всё шире.",
         {"Jetzt": "теперь", "sind+geneigt": "наклонены", "wieder": "снова", "um etwa": "примерно на",
          "sieben Grad": "семь градусов", "öffnen sich": "раскрываются",
          "von Jahr zu Jahr": "год от года", "weiter": "дальше"}),
        ("Auch der größte Saturnmond Titan ist in einem kleinen Teleskop als Lichtpunkt neben dem Planeten zu erkennen.",
         "Крупнейший спутник Сатурна Титан тоже виден в небольшой телескоп как светлая точка рядом с планетой.",
         {"Auch": "тоже", "größte": "крупнейший", "Saturnmond": "спутник Сатурна", "Titan": "Титан",
          "ist+zu erkennen": "различим", "in einem kleinen Teleskop": "в небольшой телескоп",
          "als": "как", "Lichtpunkt": "светлая точка", "neben dem Planeten": "рядом с планетой"}),
    ],
    ('fig', 'hubble'),
    [
        ("Wie Saturn aus der Nähe aussieht, zeigen Bilder der beiden großen Weltraumteleskope.",
         "Как Сатурн выглядит вблизи, показывают снимки двух больших космических телескопов.",
         {"Wie": "как", "Saturn": "Сатурн", "aus der Nähe": "вблизи", "aussieht": "выглядит",
          "zeigen": "показывают", "Bilder": "снимки", "der beiden": "обоих", "großen": "больших",
          "Weltraumteleskope": "космических телескопов"}),
        ("Hubble fotografiert ihn im sichtbaren Licht, das James-Webb-Teleskop dagegen im Infrarot.",
         "«Хаббл» снимает его в видимом свете, а телескоп «Джеймс Уэбб» — в инфракрасном.",
         {"Hubble": "Хаббл", "fotografiert": "фотографирует", "ihn": "его",
          "im sichtbaren Licht": "в видимом свете", "James-Webb-Teleskop": "телескоп «Джеймс Уэбб»",
          "dagegen": "напротив", "im Infrarot": "в инфракрасном"}),
        ("Im Infrarot leuchten die eisigen Ringe besonders hell.",
         "В инфракрасном свете ледяные кольца сияют особенно ярко.",
         {"Im Infrarot": "в инфракрасном", "leuchten": "светятся", "eisigen": "ледяные",
          "Ringe": "кольца", "besonders": "особенно", "hell": "ярко"}),
    ],
    [
        ("Die nächste Opposition folgt Mitte Oktober 2027, dann sind die Ringe noch etwas weiter geöffnet.",
         "Следующее противостояние будет в середине октября 2027 года — тогда кольца раскроются ещё немного шире.",
         {"nächste": "следующее", "Opposition": "противостояние", "folgt": "последует",
          "Mitte Oktober": "в середине октября", "dann": "тогда", "sind+geöffnet": "раскрыты",
          "Ringe": "кольца", "noch etwas": "ещё немного", "weiter": "шире"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  3. Crew-13 — экипаж на МКС
# ════════════════════════════════════════════════════════════════════
ARTICLES['crew-13-iss-2026'] = [
    ('fig', 'launch'),
    [
        ("Am 1. Oktober 2026 ist die Mission Crew-13 vom Weltraumbahnhof Cape Canaveral in Florida gestartet.",
         "1 октября 2026 года с космодрома на мысе Канаверал во Флориде стартовала миссия Crew-13.",
         {"Am": "", "Oktober": "октября", "ist+gestartet": "стартовала", "Mission": "миссия",
          "vom Weltraumbahnhof": "с космодрома", "Cape Canaveral": "мыс Канаверал",
          "in Florida": "во Флориде"}),
        ("Eine Falcon-9-Rakete von SpaceX hob um 11:10 Uhr Ortszeit ab.",
         "Ракета Falcon 9 компании SpaceX стартовала в 11:10 по местному времени.",
         {"Rakete": "ракета", "von SpaceX": "компании SpaceX", "hob+ab": "взлетела", "um": "в",
          "Uhr": "часов", "Ortszeit": "местного времени"}),
        ("An Bord der Kapsel Crew Dragon »Grace« saßen vier Raumfahrer aus drei Ländern.",
         "На борту капсулы Crew Dragon «Grace» находились четверо космонавтов из трёх стран.",
         {"An Bord": "на борту", "der Kapsel": "капсулы", "saßen": "сидели", "vier": "четыре",
          "Raumfahrer": "космонавта", "aus drei Ländern": "из трёх стран"}),
    ],
    [
        ("Kommandantin ist die NASA-Astronautin Jessica Watkins, eine Geologin, die bereits zum zweiten Mal ins All fliegt.",
         "Командир — астронавт NASA Джессика Уоткинс, геолог, которая летит в космос уже во второй раз.",
         {"Kommandantin": "командир", "ist": "—", "NASA-Astronautin": "астронавт NASA",
          "Geologin": "геолог", "die#2": "которая", "bereits": "уже", "zum zweiten Mal": "во второй раз",
          "ins All": "в космос", "fliegt": "летит"}),
        ("Für Pilot Luke Delaney, den russischen Kosmonauten Sergei Teterjatnikow und den Kanadier Joshua Kutryk ist es der erste Raumflug.",
         "Для пилота Люка Делейни, российского космонавта Сергея Тетерятникова и канадца Джошуа Кутрика это первый космический полёт.",
         {"Für": "для", "Pilot": "пилота", "russischen": "российского", "Kosmonauten": "космонавта",
          "Kanadier": "канадца", "ist es": "это", "erste": "первый", "Raumflug": "космический полёт"}),
    ],
    ('fig', 'crew'),
    [
        ("Schon acht Stunden nach dem Start legte die Kapsel an der Internationalen Raumstation an.",
         "Уже через восемь часов после старта капсула пристыковалась к Международной космической станции.",
         {"Schon": "уже", "acht Stunden": "восемь часов", "nach dem Start": "после старта",
          "legte+an#2": "причалила", "Kapsel": "капсула", "an der": "к",
          "Internationalen Raumstation": "Международной космической станции"}),
        ("Für eine Besatzung der NASA ist das ein Rekord.",
         "Для экипажа NASA это рекорд.",
         {"Für": "для", "Besatzung": "экипажа", "ist das": "это", "Rekord": "рекорд"}),
        ("Die Kopplung erfolgte am Modul Harmony, während die Station über dem Nordostpazifik flog.",
         "Стыковка прошла к модулю Harmony, когда станция пролетала над северо-восточной частью Тихого океана.",
         {"Kopplung": "стыковка", "erfolgte": "произошла", "am Modul": "к модулю", "während": "пока",
          "Station": "станция", "über": "над", "dem Nordostpazifik": "северо-востоком Тихого океана",
          "flog": "летела"}),
    ],
    [
        ("Die vier Raumfahrer bleiben etwa sechs Monate an Bord.",
         "Четверо космонавтов пробудут на борту около шести месяцев.",
         {"vier": "четыре", "Raumfahrer": "космонавта", "bleiben": "останутся", "etwa": "около",
          "sechs Monate": "шесть месяцев", "an Bord": "на борту"}),
        ("Sie sollen die Station warten, mehrere Außeneinsätze absolvieren und Frachtschiffe in Empfang nehmen.",
         "Им предстоит обслуживать станцию, совершить несколько выходов в открытый космос и принимать грузовые корабли.",
         {"sollen": "должны", "Station": "станцию", "warten": "обслуживать", "mehrere": "несколько",
          "Außeneinsätze": "выходов в космос", "absolvieren": "выполнить",
          "Frachtschiffe": "грузовые корабли", "in Empfang nehmen": "принимать"}),
        ("Auf dem Programm stehen außerdem zahlreiche Experimente, etwa mit Stammzellen, die bei der Behandlung von Herzkrankheiten und Parkinson helfen könnten.",
         "В программе также многочисленные эксперименты — например, со стволовыми клетками, которые могли бы помочь в лечении болезней сердца и Паркинсона.",
         {"Auf dem Programm": "в программе", "stehen": "стоят", "außerdem": "кроме того",
          "zahlreiche": "многочисленные", "Experimente": "эксперименты", "etwa": "например",
          "mit Stammzellen": "со стволовыми клетками", "die": "которые",
          "bei der Behandlung": "при лечении", "von Herzkrankheiten": "болезней сердца",
          "Parkinson": "Паркинсона", "helfen": "помочь", "könnten": "могли бы"}),
        ("Andere Versuche beschäftigen sich mit dem Anbau von Pflanzen im All.",
         "Другие опыты посвящены выращиванию растений в космосе.",
         {"Andere": "другие", "Versuche": "опыты", "beschäftigen sich": "занимаются",
          "mit dem Anbau": "выращиванием", "von Pflanzen": "растений", "im All": "в космосе"}),
    ],
    ('fig', 'sunset'),
    [
        ("Für Joshua Kutryk ist die Mission auch privat etwas Besonderes, denn seine Frau erwartet in einigen Wochen das dritte Kind.",
         "Для Джошуа Кутрика миссия особенная и в личном плане: через несколько недель его жена ждёт третьего ребёнка.",
         {"Für": "для", "ist": "", "Mission": "миссия", "auch": "и", "privat": "в личном плане",
          "etwas Besonderes": "нечто особенное", "denn": "ведь", "seine Frau": "его жена",
          "erwartet": "ждёт", "in einigen Wochen": "через несколько недель", "dritte": "третьего",
          "Kind": "ребёнка"}),
        ("Die Geburt wird er also aus dem Weltraum miterleben.",
         "Значит, рождение ребёнка он переживёт из космоса.",
         {"Geburt": "рождение", "wird+miterleben": "переживёт вместе", "also": "значит",
          "aus dem Weltraum": "из космоса"}),
        ("Die bisherige Besatzung Crew-12 soll die Station frühestens am 7. Oktober verlassen.",
         "Предыдущий экипаж Crew-12 должен покинуть станцию не раньше 7 октября.",
         {"bisherige": "прежний", "Besatzung": "экипаж", "soll": "должен", "Station": "станцию",
          "frühestens": "не раньше", "am": "", "Oktober": "октября", "verlassen": "покинуть"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  4. Экономика — правительство повысило прогноз роста
# ════════════════════════════════════════════════════════════════════
ARTICLES['wirtschaft-prognose-2026'] = [
    ('fig', 'hafen'),
    [
        ("Die Bundesregierung ist für die deutsche Wirtschaft deutlich optimistischer geworden.",
         "Федеральное правительство стало заметно оптимистичнее смотреть на экономику Германии.",
         {"Bundesregierung": "федеральное правительство", "ist+geworden": "стало", "für": "в отношении",
          "deutsche": "немецкой", "Wirtschaft": "экономики", "deutlich": "заметно",
          "optimistischer": "оптимистичнее"}),
        ("Nach Informationen der Nachrichtenagentur Reuters rechnet sie für das Jahr 2026 jetzt mit einem Wachstum von 1,3 Prozent.",
         "По данным агентства Reuters, теперь оно рассчитывает на рост в 2026 году на 1,3 процента.",
         {"Nach Informationen": "по информации", "der Nachrichtenagentur": "информагентства",
          "rechnet+mit": "рассчитывает на", "für das Jahr": "на год", "jetzt": "теперь",
          "einem": "", "Wachstum": "рост", "von": "в", "Prozent": "процента"}),
        ("Im Frühjahr hatte sie nur 0,5 Prozent erwartet.",
         "Весной оно ожидало лишь 0,5 процента.",
         {"Im Frühjahr": "весной", "hatte+erwartet": "ожидало", "nur": "лишь", "Prozent": "процента"}),
    ],
    [
        ("Auch für 2027 wurde die Prognose angehoben: von 0,9 auf 1,1 Prozent.",
         "Прогноз на 2027 год тоже повысили: с 0,9 до 1,1 процента.",
         {"Auch": "тоже", "für": "на", "wurde+angehoben": "был повышен", "Prognose": "прогноз",
          "von": "с", "auf": "до", "Prozent": "процента"}),
        ("Für 2028 erwartet die Regierung ein Plus von 0,6 Prozent.",
         "На 2028 год правительство ожидает прирост в 0,6 процента.",
         {"Für": "на", "erwartet": "ожидает", "Regierung": "правительство", "Plus": "прирост",
          "von": "в", "Prozent": "процента"}),
        ("Offiziell will sie die neuen Zahlen am 8. Oktober vorstellen.",
         "Официально новые цифры оно собирается представить 8 октября.",
         {"Offiziell": "официально", "will": "хочет", "neuen": "новые", "Zahlen": "цифры",
          "am": "", "Oktober": "октября", "vorstellen": "представить"}),
    ],
    ('fig', 'bruecke'),
    [
        ("Der wichtigste Grund für den Aufschwung sind die Investitionen des Staates.",
         "Главная причина подъёма — государственные инвестиции.",
         {"wichtigste": "важнейшая", "Grund": "причина", "für den Aufschwung": "подъёма",
          "sind": "—", "Investitionen": "инвестиции", "des Staates": "государства"}),
        ("Mit neuen Schulden finanziert der Bund Straßen, Brücken und Schienen, außerdem gibt er mehr Geld für die Bundeswehr aus.",
         "На новые долги федерация финансирует дороги, мосты и железные дороги, а кроме того тратит больше денег на бундесвер.",
         {"Mit neuen Schulden": "на новые долги", "finanziert": "финансирует", "Bund": "федерация",
          "Straßen": "дороги", "Brücken": "мосты", "Schienen": "рельсы", "außerdem": "кроме того",
          "gibt+aus": "тратит", "mehr Geld": "больше денег", "für die Bundeswehr": "на бундесвер"}),
        ("Davon profitieren vor allem die Bauwirtschaft und die Industrie.",
         "Выигрывают от этого прежде всего строительная отрасль и промышленность.",
         {"Davon": "от этого", "profitieren": "выигрывают", "vor allem": "прежде всего",
          "Bauwirtschaft": "строительная отрасль", "Industrie": "промышленность"}),
    ],
    [
        ("Bei den Exporten rechnet die Regierung in diesem Jahr mit einem Plus von 3,7 Prozent.",
         "По экспорту правительство рассчитывает в этом году на прирост в 3,7 процента.",
         {"Bei den Exporten": "по экспорту", "rechnet+mit": "рассчитывает на", "Regierung": "правительство",
          "in diesem Jahr": "в этом году", "einem": "", "Plus": "прирост", "von": "в", "Prozent": "процента"}),
        ("Dabei bleibt die Lage schwierig: Die Zölle der USA verunsichern viele Unternehmen, und der Konflikt im Nahen Osten hat das Öl teurer gemacht.",
         "При этом ситуация остаётся сложной: пошлины США тревожат многие компании, а конфликт на Ближнем Востоке сделал нефть дороже.",
         {"Dabei": "при этом", "bleibt": "остаётся", "Lage": "ситуация", "schwierig": "сложной",
          "Zölle": "пошлины", "der USA": "США", "verunsichern": "тревожат", "viele": "многие",
          "Unternehmen": "компании", "Konflikt": "конфликт", "im Nahen Osten": "на Ближнем Востоке",
          "hat+gemacht": "сделал", "Öl": "нефть", "teurer": "дороже"}),
    ],
    [
        ("Die Verbraucher spüren das vor allem an den Preisen.",
         "Потребители ощущают это прежде всего по ценам.",
         {"Verbraucher": "потребители", "spüren": "ощущают", "das": "это", "vor allem": "прежде всего",
          "an den Preisen": "по ценам"}),
        ("Benzin und Diesel kosten deutlich mehr als noch vor einem Jahr.",
         "Бензин и дизель стоят заметно больше, чем год назад.",
         {"Benzin": "бензин", "Diesel": "дизель", "kosten": "стоят", "deutlich": "заметно",
          "mehr als": "больше, чем", "noch": "ещё", "vor einem Jahr": "год назад"}),
        ("Die Inflation soll 2026 bei 2,7 Prozent liegen und 2027 sogar auf 3,0 Prozent steigen.",
         "Инфляция в 2026 году должна составить 2,7 процента, а в 2027-м даже вырасти до 3,0 процента.",
         {"Inflation": "инфляция", "soll": "должна", "bei": "на уровне", "Prozent": "процента",
          "liegen": "находиться", "sogar": "даже", "auf": "до", "Prozent#2": "процента",
          "steigen": "вырасти"}),
        ("Deshalb kaufen viele Menschen vorsichtig ein: Der private Konsum wächst in diesem Jahr voraussichtlich nur um 0,8 Prozent.",
         "Поэтому многие покупают осторожно: частное потребление в этом году, по прогнозу, вырастет лишь на 0,8 процента.",
         {"Deshalb": "поэтому", "kaufen+ein": "делают покупки", "viele Menschen": "многие люди",
          "vorsichtig": "осторожно", "private": "частное", "Konsum": "потребление", "wächst": "растёт",
          "in diesem Jahr": "в этом году", "voraussichtlich": "предположительно", "nur": "лишь",
          "um": "на", "Prozent": "процента"}),
    ],
    ('fig', 'bundesbank'),
    [
        ("Auch die Bundesbank ist zuversichtlicher geworden.",
         "Бундесбанк тоже стал смотреть в будущее увереннее.",
         {"Auch": "тоже", "Bundesbank": "Бундесбанк", "ist+geworden": "стал",
          "zuversichtlicher": "увереннее"}),
        ("Ihr Präsident Joachim Nagel sagte, die Wirtschaft könne in diesem Jahr um etwa ein Prozent wachsen.",
         "Его президент Йоахим Нагель сказал, что экономика в этом году может вырасти примерно на один процент.",
         {"Ihr": "его", "Präsident": "президент", "sagte": "сказал", "Wirtschaft": "экономика",
          "könne": "может (по его словам)", "in diesem Jahr": "в этом году", "um etwa": "примерно на",
          "ein Prozent": "один процент", "wachsen": "вырасти"}),
        ("Nach drei Jahren ohne Wachstum wäre das ein kleines, aber wichtiges Signal.",
         "После трёх лет без роста это был бы небольшой, но важный сигнал.",
         {"Nach drei Jahren": "после трёх лет", "ohne Wachstum": "без роста", "wäre": "был бы",
          "das": "это", "kleines": "небольшой", "aber": "но", "wichtiges": "важный", "Signal": "сигнал"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  5. События — День немецкого единства в Бремене
# ════════════════════════════════════════════════════════════════════
ARTICLES['einheitsfeier-bremen-2026'] = [
    ('fig', 'markt'),
    [
        ("Drei Tage lang hat Bremen den Tag der Deutschen Einheit gefeiert.",
         "Три дня Бремен праздновал День немецкого единства.",
         {"Drei Tage lang": "три дня", "hat+gefeiert": "праздновал", "Bremen": "Бремен",
          "Tag der Deutschen Einheit": "День немецкого единства"}),
        ("Vom 2. bis zum 4. Oktober kamen rund 550.000 Besucher in die Stadt an der Weser.",
         "Со 2 по 4 октября в город на Везере приехали около 550 000 гостей.",
         {"Vom": "с", "bis zum": "по", "Oktober": "октября", "kamen": "пришли", "rund": "около",
          "Besucher": "посетителей", "in die Stadt": "в город", "an der Weser": "на Везере"}),
        ("Erwartet hatte man nur etwa 450.000 Gäste.",
         "Ожидали всего около 450 000 гостей.",
         {"Erwartet+hatte": "ожидали", "man": "", "nur": "лишь", "etwa": "около", "Gäste": "гостей"}),
    ],
    [
        ("Die zentrale Feier findet jedes Jahr in dem Bundesland statt, das gerade den Vorsitz im Bundesrat hat.",
         "Главный праздник каждый год проходит в той федеральной земле, которая в этот момент председательствует в бундесрате.",
         {"zentrale": "центральный", "Feier": "праздник", "findet+statt": "проходит",
          "jedes Jahr": "каждый год", "in dem Bundesland": "в федеральной земле", "das": "которая",
          "gerade": "как раз", "den Vorsitz": "председательство", "im Bundesrat": "в бундесрате", "hat": "имеет"}),
        ("In diesem Jahr war das Bremen – nach 1994 und 2010 schon zum dritten Mal.",
         "В этом году это был Бремен — уже в третий раз после 1994 и 2010 годов.",
         {"In diesem Jahr": "в этом году", "war": "был", "das": "это", "Bremen": "Бремен",
          "nach": "после", "schon": "уже", "zum dritten Mal": "в третий раз"}),
        ("Das Motto lautete »Viele Stärken – ein Land«.",
         "Девиз звучал так: «Много сильных сторон — одна страна».",
         {"Motto": "девиз", "lautete": "гласил", "Viele": "много", "Stärken": "сильных сторон",
          "ein Land": "одна страна"}),
    ],
    ('fig', 'glocke'),
    [
        ("Am 3. Oktober begann der offizielle Teil mit einem Gottesdienst im Bremer Dom.",
         "3 октября официальная часть началась с богослужения в Бременском соборе.",
         {"Am": "", "Oktober": "октября", "begann": "началась", "offizielle": "официальная",
          "Teil": "часть", "mit einem Gottesdienst": "с богослужения", "im Bremer Dom": "в Бременском соборе"}),
        ("Danach folgte ein Festakt im Konzerthaus »Die Glocke«.",
         "Затем последовало торжественное собрание в концертном зале «Колокол».",
         {"Danach": "затем", "folgte": "последовал", "Festakt": "торжественный акт",
          "im Konzerthaus": "в концертном зале", "Die Glocke": "«Колокол»"}),
        ("Dort hielt Bundespräsident Frank-Walter Steinmeier eine Rede.",
         "Там выступил с речью федеральный президент Франк-Вальтер Штайнмайер.",
         {"Dort": "там", "hielt+Rede": "произнёс речь", "Bundespräsident": "федеральный президент",
          "eine": ""}),
    ],
    [
        ("Er erinnerte an die Friedliche Revolution von 1989 und an das Glück der Wiedervereinigung.",
         "Он напомнил о Мирной революции 1989 года и о счастье воссоединения.",
         {"erinnerte+an": "напомнил о", "Friedliche Revolution": "Мирную революцию", "von": "",
          "an#2": "о", "Glück": "счастье", "der Wiedervereinigung": "воссоединения"}),
        ("Gleichzeitig warnte er vor Extremismus und Spaltung: Die Demagogie extremistischer Kräfte gefährde nicht nur Freiheit und Demokratie, sondern auch die Einheit.",
         "Вместе с тем он предостерёг от экстремизма и раскола: демагогия экстремистских сил, по его словам, угрожает не только свободе и демократии, но и единству.",
         {"Gleichzeitig": "одновременно", "warnte+vor": "предостерёг от", "Extremismus": "экстремизма",
          "Spaltung": "раскола", "Demagogie": "демагогия", "extremistischer Kräfte": "экстремистских сил",
          "gefährde": "угрожает (по его словам)", "nicht nur": "не только", "Freiheit": "свободе",
          "Demokratie": "демократии", "sondern auch": "но и", "Einheit": "единству"}),
        ("Am Ende rief er: »Unser Deutschland ist ein gutes Land! Sorgen wir dafür, dass es so bleibt!«",
         "В конце он призвал: «Наша Германия — хорошая страна! Позаботимся о том, чтобы так и оставалось!»",
         {"Am Ende": "в конце", "rief": "воскликнул", "Unser": "наша", "ist": "—", "gutes Land": "хорошая страна",
          "Sorgen+dafür": "позаботимся о том", "dass": "чтобы", "es": "", "so": "так", "bleibt": "оставалось"}),
    ],
    ('fig', 'musikanten'),
    [
        ("In der ganzen Innenstadt fand ein großes Bürgerfest statt.",
         "По всему центру города прошёл большой народный праздник.",
         {"In der ganzen Innenstadt": "по всему центру", "fand+statt": "прошёл", "großes": "большой",
          "Bürgerfest": "народный праздник"}),
        ("Auf mehreren Bühnen gab es Konzerte, Theater und Lesungen, unter anderem mit den Fantastischen Vier.",
         "На нескольких сценах шли концерты, спектакли и чтения — среди прочих выступили Die Fantastischen Vier.",
         {"Auf mehreren Bühnen": "на нескольких сценах", "gab es": "были", "Konzerte": "концерты",
          "Theater": "театр", "Lesungen": "чтения", "unter anderem": "среди прочего",
          "mit den Fantastischen Vier": "с группой Die Fantastischen Vier"}),
        ("Auf der Ländermeile am Osterdeich stellten sich alle 16 Bundesländer vor.",
         "На «Миле земель» у дамбы Остердайх представились все 16 федеральных земель.",
         {"Auf der Ländermeile": "на «Миле земель»", "am Osterdeich": "у Остердайха",
          "stellten+vor": "представились", "sich": "", "alle": "все", "Bundesländer": "федеральные земли"}),
        ("Busse und Bahnen in der ganzen Region waren kostenlos.",
         "Автобусы и поезда во всём регионе были бесплатными.",
         {"Busse": "автобусы", "Bahnen": "поезда", "in der ganzen Region": "во всём регионе",
          "waren": "были", "kostenlos": "бесплатными"}),
    ],
    ('fig', 'schlachte'),
    [
        ("Rund 4000 Polizistinnen und Polizisten sorgten für Sicherheit.",
         "Около 4000 полицейских обеспечивали безопасность.",
         {"Rund": "около", "Polizistinnen und Polizisten": "полицейские", "sorgten+für": "обеспечивали",
          "Sicherheit": "безопасность"}),
        ("Bis auf einzelne Zusammenstöße bei einer Demonstration blieb es friedlich.",
         "Если не считать отдельных стычек на одной демонстрации, всё прошло мирно.",
         {"Bis auf": "за исключением", "einzelne": "отдельных", "Zusammenstöße": "столкновений",
          "bei einer Demonstration": "на демонстрации", "blieb": "оставалось", "es": "", "friedlich": "мирно"}),
        ("Bürgermeister Andreas Bovenschulte sprach von drei wunderbaren Tagen.",
         "Бургомистр Андреас Бовеншульте говорил о трёх замечательных днях.",
         {"Bürgermeister": "бургомистр", "sprach+von": "говорил о", "drei": "трёх",
          "wunderbaren": "замечательных", "Tagen": "днях"}),
        ("Im nächsten Jahr ist Düsseldorf an der Reihe.",
         "В следующем году очередь Дюссельдорфа.",
         {"Im nächsten Jahr": "в следующем году", "ist+an der Reihe": "очередь (за)",
          "Düsseldorf": "Дюссельдорф"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  6. Экономика — налог на пластиковую упаковку с 2027 года
# ════════════════════════════════════════════════════════════════════
ARTICLES['plastiksteuer-2027'] = [
    ('fig', 'regal'),
    [
        ("Die Bundesregierung will eine neue Steuer einführen: eine Steuer auf Verpackungen aus Plastik.",
         "Федеральное правительство хочет ввести новый налог — налог на упаковку из пластика.",
         {"Bundesregierung": "федеральное правительство", "will": "хочет", "neue": "новый",
          "Steuer": "налог", "einführen": "ввести", "Steuer#2": "налог", "auf": "на",
          "Verpackungen": "упаковку", "aus Plastik": "из пластика"}),
        ("Darüber berichteten am 5. Oktober mehrere Zeitungen, darunter das Handelsblatt und der Tagesspiegel.",
         "Об этом 5 октября сообщили несколько газет, среди них Handelsblatt и Tagesspiegel.",
         {"Darüber": "об этом", "berichteten": "сообщили", "am": "", "Oktober": "октября",
          "mehrere": "несколько", "Zeitungen": "газет", "darunter": "среди них"}),
        ("Ihnen liegt ein Gesetzentwurf des Finanzministeriums vor.",
         "В их распоряжении оказался законопроект министерства финансов.",
         {"Ihnen": "у них", "liegt+vor": "имеется", "Gesetzentwurf": "законопроект",
          "des Finanzministeriums": "министерства финансов"}),
        ("Die Steuer soll am 1. Juli 2027 starten.",
         "Налог должен заработать 1 июля 2027 года.",
         {"Steuer": "налог", "soll": "должен", "am": "", "Juli": "июля", "starten": "начаться"}),
    ],
    [
        ("Pro Tonne Kunststoff sollen die Firmen 550 Euro zahlen, also 55 Cent pro Kilogramm.",
         "За тонну пластика фирмы должны будут платить 550 евро, то есть 55 центов за килограмм.",
         {"Pro Tonne": "за тонну", "Kunststoff": "пластика", "sollen": "должны",
          "Firmen": "фирмы", "zahlen": "платить", "also": "то есть", "pro Kilogramm": "за килограмм"}),
        ("Betroffen sind Verpackungen, Folien und Verbundverpackungen, wenn ihr Anteil an Kunststoff höher als fünf Prozent ist.",
         "Это касается упаковки, плёнки и комбинированной упаковки, если доля пластика в них больше пяти процентов.",
         {"Betroffen sind": "затронуты", "Verpackungen": "упаковка", "Folien": "плёнки",
          "Verbundverpackungen": "комбинированная упаковка", "wenn": "если", "ihr": "их",
          "Anteil an Kunststoff": "доля пластика", "höher als": "выше, чем",
          "fünf Prozent": "пять процентов"}),
        ("Zahlen müssen die Hersteller und die Firmen, die Verpackungen nach Deutschland importieren.",
         "Платить должны производители и фирмы, которые ввозят упаковку в Германию.",
         {"Zahlen müssen": "платить должны", "Hersteller": "производители", "Firmen": "фирмы",
          "die#3": "которые", "Verpackungen": "упаковку", "nach Deutschland": "в Германию",
          "importieren": "ввозят"}),
    ],
    ('fig', 'tomaten'),
    [
        ("Für das Jahr 2027 rechnet Finanzminister Lars Klingbeil mit Einnahmen von 805 Millionen Euro.",
         "На 2027 год министр финансов Ларс Клингбайль рассчитывает на доходы в 805 миллионов евро.",
         {"Für das Jahr": "на год", "rechnet+mit": "рассчитывает на", "Finanzminister": "министр финансов",
          "Einnahmen": "доходы", "von": "в", "Millionen": "миллионов"}),
        ("Ab 2028 sollen es jedes Jahr rund 1,4 Milliarden Euro sein.",
         "С 2028 года это должно быть около 1,4 миллиарда евро ежегодно.",
         {"Ab": "с", "sollen+sein": "должно быть", "es": "это", "jedes Jahr": "каждый год",
          "rund": "около", "Milliarden": "миллиарда"}),
        ("Die Steuer soll aber nicht nur Geld bringen.",
         "Но налог должен не только приносить деньги.",
         {"Steuer": "налог", "soll": "должен", "aber": "но", "nicht nur": "не только",
          "Geld": "деньги", "bringen": "приносить"}),
        ("Nach Angaben des Ministeriums kann sie auch helfen, weniger Plastik zu verbrauchen.",
         "По данным министерства, он может также помочь расходовать меньше пластика.",
         {"Nach Angaben": "по данным", "des Ministeriums": "министерства", "kann": "может",
          "sie": "он (налог)", "auch": "также", "helfen": "помочь", "weniger": "меньше",
          "Plastik": "пластика", "zu verbrauchen": "расходовать"}),
    ],
    ('fig', 'gelbersack'),
    [
        ("Hintergrund ist eine Abgabe der Europäischen Union.",
         "Предыстория — сбор Европейского союза.",
         {"Hintergrund": "предыстория", "ist": "—", "Abgabe": "сбор",
          "der Europäischen Union": "Европейского союза"}),
        ("Seit 2021 muss jedes Land der EU für Plastikmüll, der nicht recycelt wird, 80 Cent pro Kilogramm nach Brüssel überweisen.",
         "С 2021 года каждая страна ЕС за пластиковый мусор, который не перерабатывается, должна перечислять в Брюссель 80 центов за килограмм.",
         {"Seit": "с", "muss": "должна", "jedes Land": "каждая страна", "der EU": "ЕС",
          "für Plastikmüll": "за пластиковый мусор", "der#2": "который", "nicht": "не",
          "recycelt wird": "перерабатывается", "pro Kilogramm": "за килограмм",
          "nach Brüssel": "в Брюссель", "überweisen": "перечислять"}),
        ("Deutschland zahlt dafür bisher jedes Jahr rund 1,3 bis 1,4 Milliarden Euro aus dem Bundeshaushalt.",
         "Германия до сих пор платит за это ежегодно около 1,3–1,4 миллиарда евро из федерального бюджета.",
         {"zahlt": "платит", "dafür": "за это", "bisher": "до сих пор", "jedes Jahr": "каждый год",
          "rund": "около", "bis": "до", "Milliarden": "миллиарда",
          "aus dem Bundeshaushalt": "из федерального бюджета"}),
        ("Künftig sollen dieses Geld die Unternehmen aufbringen.",
         "В будущем эти деньги должны находить компании.",
         {"Künftig": "в будущем", "sollen": "должны", "dieses Geld": "эти деньги",
          "Unternehmen": "компании", "aufbringen": "изыскать (деньги)"}),
    ],
    [
        ("Am Ende zahlen aber wohl die Kunden.",
         "Но в итоге платить, вероятно, будут покупатели.",
         {"Am Ende": "в итоге", "zahlen": "платят", "aber": "но", "wohl": "вероятно",
          "Kunden": "покупатели"}),
        ("Nach dem Entwurf dürfen die Firmen die Kosten an ihre Kunden weitergeben.",
         "По проекту фирмы могут переложить расходы на своих покупателей.",
         {"Nach dem Entwurf": "по проекту", "dürfen": "имеют право", "Firmen": "фирмы",
          "Kosten": "расходы", "an ihre Kunden": "на своих покупателей", "weitergeben": "передать"}),
        ("Joghurt, Wurst oder Getränke in Plastikflaschen könnten deshalb etwas teurer werden.",
         "Поэтому йогурт, колбаса или напитки в пластиковых бутылках могут немного подорожать.",
         {"Joghurt": "йогурт", "Wurst": "колбаса", "oder": "или", "Getränke": "напитки",
          "in Plastikflaschen": "в пластиковых бутылках", "könnten": "могли бы",
          "deshalb": "поэтому", "etwas": "немного", "teurer werden": "подорожать"}),
    ],
    ('fig', 'ministerium'),
    [
        ("Die Wirtschaft ist unzufrieden.",
         "Бизнес недоволен.",
         {"Wirtschaft": "экономика, бизнес", "ist": "", "unzufrieden": "недоволен"}),
        ("Der Handelsverband HDE spricht von einem „Bruch des Koalitionsvertrags“.",
         "Торговый союз HDE говорит о «нарушении коалиционного договора».",
         {"Handelsverband": "торговый союз", "spricht+von": "говорит о", "einem": "",
          "Bruch": "нарушении", "des Koalitionsvertrags": "коалиционного договора"}),
        ("Die Kunststoffindustrie warnt, dass Firmen dann öfter andere Materialien nehmen, die sich schlechter recyceln lassen.",
         "Производители пластика предупреждают, что фирмы тогда чаще будут брать другие материалы, которые хуже поддаются переработке.",
         {"Kunststoffindustrie": "индустрия пластика", "warnt": "предупреждает", "dass": "что",
          "Firmen": "фирмы", "dann": "тогда", "öfter": "чаще", "andere": "другие",
          "Materialien": "материалы", "nehmen": "берут", "die": "которые",
          "sich+lassen": "поддаются", "schlechter": "хуже", "recyceln": "переработке"}),
        ("Außerdem kostet die Steuer selbst Geld: Für den Zoll und die nötige Technik plant der Bund bis 2029 rund 284 Millionen Euro ein.",
         "К тому же сам налог стоит денег: на таможню и нужную технику федерация закладывает до 2029 года около 284 миллионов евро.",
         {"Außerdem": "к тому же", "kostet": "стоит", "Steuer": "налог", "selbst": "сам",
          "Geld": "денег", "Für den Zoll": "на таможню", "nötige": "нужную", "Technik": "технику",
          "plant+ein": "закладывает", "Bund": "федерация", "bis": "до", "rund": "около",
          "Millionen": "миллионов"}),
        ("Bevor die Steuer kommt, muss noch der Bundestag zustimmen.",
         "Прежде чем налог появится, его ещё должен одобрить бундестаг.",
         {"Bevor": "прежде чем", "Steuer": "налог", "kommt": "появится", "muss": "должен",
          "noch": "ещё", "Bundestag": "бундестаг", "zustimmen": "одобрить"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  7. Наука — Нобелевская премия по физике 2026
# ════════════════════════════════════════════════════════════════════
ARTICLES['nobelpreis-physik-2026'] = [
    ('fig', 'icecube'),
    [
        ("Der Nobelpreis für Physik geht in diesem Jahr an den Forscher Francis Halzen.",
         "Нобелевская премия по физике в этом году достаётся исследователю Франсису Халзену.",
         {"Nobelpreis": "Нобелевская премия", "für Physik": "по физике", "geht+an": "достаётся",
          "in diesem Jahr": "в этом году", "Forscher": "исследователю"}),
        ("Das gab die Königlich Schwedische Akademie der Wissenschaften am 6. Oktober in Stockholm bekannt.",
         "Об этом 6 октября объявила в Стокгольме Шведская королевская академия наук.",
         {"Das": "это", "gab+bekannt": "объявила", "Königlich Schwedische Akademie": "Шведская королевская академия",
          "der Wissenschaften": "наук", "am": "", "Oktober": "октября", "in Stockholm": "в Стокгольме"}),
        ("Halzen ist 82 Jahre alt und stammt aus Belgien.",
         "Халзену 82 года, он родом из Бельгии.",
         {"ist+alt": "ему … лет", "Jahre": "года", "stammt+aus": "родом из", "Belgien": "Бельгии"}),
        ("Seit vielen Jahren arbeitet er an einer Universität im US-Bundesstaat Wisconsin.",
         "Уже много лет он работает в университете в американском штате Висконсин.",
         {"Seit vielen Jahren": "уже много лет", "arbeitet": "работает", "an einer Universität": "в университете",
          "im US-Bundesstaat": "в штате США"}),
    ],
    [
        ("Er bekommt den Preis für seine Arbeit am Neutrino-Observatorium IceCube am Südpol.",
         "Он получает премию за свою работу над нейтринной обсерваторией IceCube на Южном полюсе.",
         {"bekommt": "получает", "Preis": "премию", "für": "за", "seine": "свою", "Arbeit": "работу",
          "am Neutrino-Observatorium": "в нейтринной обсерватории", "am#2 Südpol": "на Южном полюсе"}),
        ("Mit diesem Instrument haben Forscher zum ersten Mal Neutrinos mit sehr hoher Energie aus dem fernen Weltall nachgewiesen.",
         "С помощью этого прибора исследователи впервые зарегистрировали нейтрино очень высокой энергии из далёкого космоса.",
         {"Mit diesem Instrument": "с помощью этого прибора", "haben+nachgewiesen": "обнаружили",
          "Forscher": "исследователи", "zum ersten Mal": "впервые", "Neutrinos": "нейтрино",
          "mit sehr hoher Energie": "очень высокой энергии", "aus dem fernen Weltall": "из далёкого космоса"}),
    ],
    ('fig', 'halzen'),
    [
        ("Neutrinos sind winzige Teilchen, die fast keine Masse haben.",
         "Нейтрино — крошечные частицы, у которых почти нет массы.",
         {"Neutrinos": "нейтрино", "sind": "—", "winzige": "крошечные", "Teilchen": "частицы",
          "die": "которые", "fast keine": "почти никакой", "Masse": "массы", "haben": "имеют"}),
        ("Jede Sekunde fliegen Milliarden von ihnen durch unseren Körper, ohne dass wir etwas merken.",
         "Каждую секунду миллиарды из них пролетают сквозь наше тело, а мы ничего не замечаем.",
         {"Jede Sekunde": "каждую секунду", "fliegen": "летят", "Milliarden": "миллиарды",
          "von ihnen": "из них", "durch unseren Körper": "сквозь наше тело",
          "ohne dass": "без того, чтобы", "wir": "мы", "etwas": "что-либо", "merken": "замечаем"}),
        ("Weil sie fast nie mit anderer Materie zusammenstoßen, nennt man sie auch „Geisterteilchen“.",
         "Поскольку они почти никогда не сталкиваются с другим веществом, их называют ещё «частицами-призраками».",
         {"Weil": "поскольку", "sie": "они", "fast nie": "почти никогда", "mit anderer Materie": "с другим веществом",
          "zusammenstoßen": "сталкиваются", "nennt man": "называют", "sie#2": "их", "auch": "также",
          "Geisterteilchen": "частицы-призраки"}),
        ("„Ein Neutrino ist ein geisterhafter Bote aus dem All“, sagte Mark Pearce, der Vorsitzende des Nobelkomitees.",
         "«Нейтрино — призрачный вестник из космоса», — сказал председатель Нобелевского комитета Марк Пирс.",
         {"Ein": "", "Neutrino": "нейтрино", "ist": "—", "ein": "", "geisterhafter": "призрачный",
          "Bote": "вестник", "aus dem All": "из космоса", "sagte": "сказал",
          "Vorsitzende": "председатель", "des Nobelkomitees": "Нобелевского комитета"}),
    ],
    ('fig', 'dom'),
    [
        ("Um solche Teilchen zu fangen, braucht man einen riesigen Detektor.",
         "Чтобы поймать такие частицы, нужен огромный детектор.",
         {"Um+zu fangen": "чтобы поймать", "solche": "такие", "Teilchen": "частицы",
          "braucht man": "нужен", "einen": "", "riesigen": "огромный", "Detektor": "детектор"}),
        ("Halzens Idee war, dafür das Eis der Antarktis zu nutzen.",
         "Идея Халзена состояла в том, чтобы использовать для этого лёд Антарктиды.",
         {"Halzens": "Халзена", "Idee": "идея", "war": "была", "dafür": "для этого",
          "Eis": "лёд", "der Antarktis": "Антарктиды", "zu nutzen": "использовать"}),
        ("In einem Kubikkilometer Eis hängen über 5000 Lichtsensoren, in einer Tiefe von etwa 1,5 bis 2,5 Kilometern.",
         "В кубическом километре льда висят более 5000 световых датчиков на глубине примерно от 1,5 до 2,5 километра.",
         {"In einem Kubikkilometer": "в кубическом километре", "Eis": "льда", "hängen": "висят",
          "über": "более", "Lichtsensoren": "световых датчиков", "in einer Tiefe": "на глубине",
          "von etwa": "примерно от", "bis": "до", "Kilometern": "километров"}),
        ("Wenn ein Neutrino doch einmal mit einem Atomkern zusammenstößt, entsteht ein schwacher blauer Lichtblitz.",
         "Если нейтрино всё же столкнётся с атомным ядром, возникает слабая голубая вспышка света.",
         {"Wenn": "если", "ein": "", "Neutrino": "нейтрино", "doch einmal": "всё-таки однажды",
          "mit einem Atomkern": "с атомным ядром", "zusammenstößt": "сталкивается",
          "entsteht": "возникает", "ein#2": "", "schwacher": "слабая", "blauer": "голубая",
          "Lichtblitz": "вспышка света"}),
        ("Die Sensoren messen dieses Licht, und die Forscher können berechnen, aus welcher Richtung das Teilchen kam.",
         "Датчики измеряют этот свет, и исследователи могут вычислить, с какого направления пришла частица.",
         {"Sensoren": "датчики", "messen": "измеряют", "dieses Licht": "этот свет", "und": "и",
          "Forscher": "исследователи", "können": "могут", "berechnen": "вычислить",
          "aus welcher Richtung": "с какого направления", "Teilchen": "частица", "kam": "пришла"}),
    ],
    ('fig', 'nacht'),
    [
        ("Schon Ende der achtziger Jahre hatte Halzen die Idee mit dem Eis.",
         "Идея со льдом появилась у Халзена ещё в конце восьмидесятых годов.",
         {"Schon": "уже", "Ende": "в конце", "der achtziger Jahre": "восьмидесятых годов",
          "hatte": "имел", "Idee": "идею", "mit dem Eis": "со льдом"}),
        ("Fertig war IceCube aber erst im Jahr 2010.",
         "Но готов IceCube был лишь в 2010 году.",
         {"Fertig": "готов", "war": "был", "aber": "но", "erst": "лишь", "im Jahr": "в году"}),
        ("2013 meldete das Team die ersten Neutrinos aus dem fernen Weltall.",
         "В 2013 году команда сообщила о первых нейтрино из далёкого космоса.",
         {"meldete": "сообщила о", "Team": "команда", "ersten": "первых", "Neutrinos": "нейтрино",
          "aus dem fernen Weltall": "из далёкого космоса"}),
        ("Nach den Worten von Mark Pearce hat Halzen damit den Weg für eine neue Art von Astronomie geöffnet.",
         "По словам Марка Пирса, этим Халзен открыл путь для нового вида астрономии.",
         {"Nach den Worten": "по словам", "von": "", "hat+geöffnet": "открыл", "damit": "этим",
          "Weg": "путь", "für": "для", "neue": "нового", "Art": "вида", "von#2": "",
          "Astronomie": "астрономии"}),
    ],
    [
        ("Der Preis ist mit zwölf Millionen schwedischen Kronen dotiert, das sind gut eine Million Euro.",
         "Премия составляет двенадцать миллионов шведских крон — это чуть больше миллиона евро.",
         {"Preis": "премия", "ist+dotiert": "составляет (о премии)", "zwölf": "двенадцать",
          "Millionen": "миллионов", "schwedischen": "шведских", "Kronen": "крон", "das sind": "это",
          "gut": "с лишним", "eine Million": "один миллион"}),
        ("Überreicht wird er am 10. Dezember, dem Todestag von Alfred Nobel.",
         "Вручат её 10 декабря, в день смерти Альфреда Нобеля.",
         {"Überreicht wird": "вручается", "er": "она (премия)", "am": "", "Dezember": "декабря",
          "dem Todestag": "в день смерти", "von": ""}),
        ("Übrigens hat in diesem Jahr zum ersten Mal in der Geschichte der Akademie eine Frau den Physik-Preis verkündet: die Physikerin Ellen Moons.",
         "Кстати, в этом году впервые в истории академии премию по физике объявила женщина — физик Эллен Мунс.",
         {"Übrigens": "кстати", "hat+verkündet": "объявила", "in diesem Jahr": "в этом году",
          "zum ersten Mal": "впервые", "in der Geschichte": "в истории", "der Akademie": "академии",
          "eine": "", "Frau": "женщина", "Physik-Preis": "премию по физике", "Physikerin": "физик (женщина)"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  8. События — рекордный Октоберфест 2026
# ════════════════════════════════════════════════════════════════════
ARTICLES['oktoberfest-rekord-2026'] = [
    ('fig', 'umzug'),
    [
        ("Das Oktoberfest in München hat einen neuen Rekord aufgestellt.",
         "Октоберфест в Мюнхене установил новый рекорд.",
         {"Oktoberfest": "Октоберфест", "in München": "в Мюнхене", "hat+aufgestellt": "установил",
          "einen": "", "neuen": "новый", "Rekord": "рекорд"}),
        ("In 16 Tagen kamen nach ersten Schätzungen etwa 7,4 Millionen Gäste auf die Theresienwiese.",
         "За 16 дней, по первым оценкам, на Терезинвизе пришли около 7,4 миллиона гостей.",
         {"In": "за", "Tagen": "дней", "kamen": "пришли", "nach ersten Schätzungen": "по первым оценкам",
          "etwa": "около", "Millionen": "миллиона", "Gäste": "гостей", "auf die Theresienwiese": "на Терезинвизе"}),
        ("Das sind 900.000 Besucher mehr als im vergangenen Jahr.",
         "Это на 900 000 посетителей больше, чем в прошлом году.",
         {"Das sind": "это", "Besucher": "посетителей", "mehr als": "больше, чем",
          "im vergangenen Jahr": "в прошлом году"}),
        ("Der alte Rekord stammte aus dem Jahr 2023: Damals waren es 7,2 Millionen.",
         "Прежний рекорд был установлен в 2023 году: тогда гостей было 7,2 миллиона.",
         {"alte": "старый", "Rekord": "рекорд", "stammte+aus": "относился к", "dem Jahr": "году",
          "Damals": "тогда", "waren": "было", "es": "", "Millionen": "миллиона"}),
    ],
    [
        ("Die Stadt hatte die Gäste mit einer Kampagne gebeten, lieber an Werktagen zu kommen.",
         "Город с помощью кампании просил гостей лучше приходить в будние дни.",
         {"Stadt": "город", "hatte+gebeten": "просил", "Gäste": "гостей", "mit einer Kampagne": "кампанией",
          "lieber": "лучше", "an Werktagen": "в будние дни", "zu kommen": "приходить"}),
        ("Das hat offenbar funktioniert: Von Montag bis Donnerstag kamen in der zweiten Woche fast 29 Prozent mehr Menschen als im Vorjahr.",
         "Похоже, это сработало: с понедельника по четверг на второй неделе пришло почти на 29 процентов больше людей, чем годом ранее.",
         {"Das": "это", "hat+funktioniert": "сработало", "offenbar": "очевидно, похоже",
          "Von Montag": "с понедельника", "bis Donnerstag": "по четверг", "kamen": "пришли",
          "in der zweiten Woche": "на второй неделе", "fast": "почти", "Prozent": "процентов",
          "mehr Menschen": "больше людей", "als im Vorjahr": "чем годом ранее"}),
        ("Auch das Wetter spielte mit: Es war meist spätsommerlich warm.",
         "Погода тоже не подвела: почти всё время было тепло, по-летнему.",
         {"Auch": "тоже", "Wetter": "погода", "spielte+mit": "подыграла", "Es war": "было",
          "meist": "по большей части", "spätsommerlich": "по-позднелетнему", "warm": "тепло"}),
    ],
    ('fig', 'oidewiesn'),
    [
        ("Besonders beliebt war die Oide Wiesn, der historische Teil des Festes mit alten Karussells und Blasmusik.",
         "Особенно популярной была «Ойде Визн» — историческая часть праздника со старинными каруселями и духовой музыкой.",
         {"Besonders": "особенно", "beliebt": "популярной", "war": "была", "Oide Wiesn": "«старая Визн»",
          "historische": "историческая", "Teil": "часть", "des Festes": "праздника",
          "mit alten Karussells": "со старинными каруселями", "und": "и", "Blasmusik": "духовой музыкой"}),
        ("Dort zählte man 447.000 Gäste, fast ein Viertel mehr als 2025.",
         "Там насчитали 447 000 гостей — почти на четверть больше, чем в 2025 году.",
         {"Dort": "там", "zählte man": "насчитали", "Gäste": "гостей", "fast": "почти",
          "ein Viertel": "четверть", "mehr als": "больше, чем"}),
    ],
    [
        ("Getrunken wurden 6,7 Millionen Maß Bier.",
         "Выпито было 6,7 миллиона литровых кружек пива.",
         {"Getrunken wurden": "было выпито", "Millionen": "миллиона", "Maß": "литровых кружек",
          "Bier": "пива"}),
        ("Gleichzeitig verkauften die Wirte deutlich mehr alkoholfreies Bier: ein Plus von fast elf Prozent.",
         "Одновременно хозяева шатров продали заметно больше безалкогольного пива — прирост почти на одиннадцать процентов.",
         {"Gleichzeitig": "одновременно", "verkauften": "продали", "Wirte": "хозяева (шатров)",
          "deutlich": "заметно", "mehr": "больше", "alkoholfreies": "безалкогольного", "Bier": "пива",
          "ein": "", "Plus": "прирост", "von": "в", "fast": "почти", "elf": "одиннадцать",
          "Prozent": "процентов"}),
        ("Viele Gäste wollten offenbar einen Maßkrug als Andenken mitnehmen: Die Ordner sammelten rund 105.000 Krüge wieder ein.",
         "Многие гости, видимо, хотели унести кружку на память: распорядители собрали обратно около 105 000 кружек.",
         {"Viele": "многие", "Gäste": "гости", "wollten": "хотели", "offenbar": "видимо", "einen": "",
          "Maßkrug": "литровую кружку", "als Andenken": "на память", "mitnehmen": "унести",
          "Ordner": "распорядители", "sammelten+ein": "собрали", "rund": "около",
          "Krüge": "кружек", "wieder": "обратно"}),
    ],
    ('fig', 'karussell'),
    [
        ("Im Fundbüro landeten rund 4000 Sachen, darunter 700 Geldbeutel und 400 Handys.",
         "В бюро находок попало около 4000 вещей, среди них 700 кошельков и 400 мобильных телефонов.",
         {"Im Fundbüro": "в бюро находок", "landeten": "оказались", "rund": "около", "Sachen": "вещей",
          "darunter": "среди них", "Geldbeutel": "кошельков", "und": "и", "Handys": "мобильных"}),
        ("Auch ein Akkordeon, eine Krücke und ein Gebiss hat jemand auf der Wiesn vergessen.",
         "А ещё кто-то забыл на Визн аккордеон, костыль и вставную челюсть.",
         {"Auch": "также", "ein": "", "Akkordeon": "аккордеон", "eine": "", "Krücke": "костыль",
          "und": "и", "ein#2": "", "Gebiss": "вставную челюсть", "hat+vergessen": "забыл",
          "jemand": "кто-то", "auf der Wiesn": "на Визн"}),
        ("Getrübt wurde das Fest durch einen tödlichen Unfall an einem Fahrgeschäft.",
         "Праздник омрачил смертельный несчастный случай на одном из аттракционов.",
         {"Getrübt wurde": "был омрачён", "Fest": "праздник", "durch": "из-за",
          "einen": "", "tödlichen": "смертельного", "Unfall": "несчастного случая",
          "an einem Fahrgeschäft": "на аттракционе"}),
        ("Insgesamt zog Oberbürgermeister Dominik Krause aber eine sehr positive Bilanz: „Was für eine Bilderbuch-Wiesn! Friedlich, entspannt und gut gelaunt.“",
         "Но в целом обербургомистр Доминик Краузе подвёл очень позитивный итог: «Какая образцовая Визн! Мирная, спокойная и в хорошем настроении».",
         {"Insgesamt": "в целом", "zog+Bilanz": "подвёл итог", "Oberbürgermeister": "обербургомистр",
          "aber": "но", "eine": "", "sehr": "очень", "positive": "позитивный",
          "Was für eine": "какая", "Bilderbuch-Wiesn": "Визн как с картинки", "Friedlich": "мирная",
          "entspannt": "спокойная", "und": "и", "gut gelaunt": "в хорошем настроении"}),
    ],
]
