"""
Исходники статей раздела «Новости на немецком».

Каждая статья — список абзацев. Абзац — либо список предложений
(de, ru, g), либо фото: ('fig', имя_файла).

g — разметка подстрочника словами, а не индексами (индексы считает
tools/news/build.py по тому же WORD_RE, что у ридера):
    "Sonde"              — одно слово (первое вхождение);
    "Sonde#2"            — второе вхождение того же слова;
    "an der Erde"        — сочетание подряд идущих слов;
    "näherte+an"         — разорванная конструкция (отделяемая приставка);
    "die": ""            — не подписывать.
"""

ARTICLES = {}

# ════════════════════════════════════════════════════════════════════
#  1. Juice — гравитационный манёвр у Земли
# ════════════════════════════════════════════════════════════════════
ARTICLES['juice-erde-2026'] = [
    ('fig', 'earth'),
    [
        ("Die europäische Raumsonde Juice ist am 28. September 2026 erneut an der Erde vorbeigeflogen.",
         "Европейский зонд Juice 28 сентября 2026 года снова пролетел мимо Земли.",
         {"europäische": "европейский", "Raumsonde": "зонд", "ist+vorbeigeflogen": "пролетел мимо",
          "am": "", "September": "сентября", "erneut": "снова", "an der Erde": "Земли"}),
        ("Um 13:45 Uhr mitteleuropäischer Sommerzeit näherte sie sich unserem Planeten bis auf 8640 Kilometer.",
         "В 13:45 по центральноевропейскому летнему времени он приблизился к нашей планете на расстояние 8640 километров.",
         {"Um": "в", "Uhr": "часов", "mitteleuropäischer Sommerzeit": "по летнему времени ЦЕ",
          "näherte+sich": "приблизился", "unserem Planeten": "к нашей планете", "bis auf": "до",
          "Kilometer": "километров"}),
        ("Dabei flog sie über den Indischen Ozean.",
         "При этом он пролетал над Индийским океаном.",
         {"Dabei": "при этом", "flog": "летел", "über": "над", "Indischen Ozean": "Индийским океаном"}),
    ],
    [
        ("Das Manöver war kein Zufall, sondern ein sogenannter Swing-by.",
         "Манёвр не был случайностью — это был так называемый гравитационный манёвр.",
         {"Manöver": "манёвр", "war": "был", "kein Zufall": "не случайность", "sondern": "а",
          "sogenannter": "так называемый", "Swing-by": "гравитационный манёвр"}),
        ("Die Schwerkraft der Erde lenkte die Sonde um etwa 20 Grad ab und machte sie um 3,5 Kilometer pro Sekunde schneller.",
         "Притяжение Земли отклонило зонд примерно на 20 градусов и ускорило его на 3,5 километра в секунду.",
         {"Schwerkraft": "притяжение", "der Erde": "Земли", "lenkte+ab": "отклонило", "Sonde": "зонд",
          "um etwa": "примерно на", "Grad": "градусов", "machte+schneller": "сделало быстрее",
          "um#2": "на", "Kilometer": "километра", "pro Sekunde": "в секунду"}),
        ("Auf diese Weise spart die Mission wertvollen Treibstoff.",
         "Так миссия экономит драгоценное топливо.",
         {"Auf diese Weise": "таким образом", "spart": "экономит", "Mission": "миссия",
          "wertvollen": "ценное", "Treibstoff": "топливо"}),
    ],
    [
        ("»Der Vorbeiflug erforderte eine hochpräzise Navigation in Echtzeit«, sagte Angela Dietz, die bei der ESA für den Betrieb der Sonde verantwortlich ist.",
         "«Пролёт потребовал сверхточной навигации в реальном времени», — сказала Ангела Диц, которая отвечает в ЕКА за управление зондом.",
         {"Vorbeiflug": "пролёт", "erforderte": "потребовал", "hochpräzise": "сверхточную",
          "Navigation": "навигацию", "in Echtzeit": "в реальном времени", "sagte": "сказала",
          "die": "которая", "bei der ESA": "в ЕКА", "für": "за", "Betrieb": "управление",
          "der Sonde": "зондом", "verantwortlich ist": "отвечает"}),
        ("Von sechs geplanten Kurskorrekturen war nur eine einzige nötig.",
         "Из шести запланированных коррекций курса понадобилась лишь одна.",
         {"Von": "из", "sechs": "шести", "geplanten": "запланированных", "Kurskorrekturen": "коррекций курса",
          "war+nötig": "была нужна", "nur": "лишь", "eine einzige": "одна-единственная"}),
    ],
    [
        ("Während des Vorbeiflugs schalteten die Ingenieure mehrere Kameras und Messinstrumente ein.",
         "Во время пролёта инженеры включили несколько камер и измерительных приборов.",
         {"Während": "во время", "Vorbeiflugs": "пролёта", "schalteten+ein": "включили",
          "Ingenieure": "инженеры", "mehrere": "несколько", "Kameras": "камер",
          "Messinstrumente": "измерительных приборов"}),
        ("Eine Überwachungskamera fotografierte Afrika und Madagaskar, und in der Ecke des Bildes ist sogar der Mond als winziger grauer Punkt zu erkennen.",
         "Контрольная камера сфотографировала Африку и Мадагаскар, а в углу снимка можно различить даже Луну — крошечную серую точку.",
         {"Überwachungskamera": "контрольная камера", "fotografierte": "сфотографировала",
          "Afrika": "Африку", "Madagaskar": "Мадагаскар", "in der Ecke": "в углу",
          "des Bildes": "снимка", "ist+zu erkennen": "можно различить", "sogar": "даже",
          "Mond": "Луна", "als": "как", "winziger": "крошечная", "grauer": "серая", "Punkt": "точка"}),
    ],
    ('fig', 'madagascar'),
    [
        ("Die Navigationskamera hatte den Mond schon acht Stunden vor der größten Annäherung als schmale Sichel aufgenommen.",
         "Навигационная камера сняла Луну узким серпом ещё за восемь часов до максимального сближения.",
         {"Navigationskamera": "навигационная камера", "hatte+aufgenommen": "сняла", "den Mond": "Луну",
          "schon": "уже", "acht Stunden": "восемь часов", "vor": "до", "größten": "наибольшего",
          "Annäherung": "сближения", "als": "как", "schmale": "узкий", "Sichel": "серп"}),
    ],
    ('fig', 'moon'),
    [
        ("Für die Forscher ist ein solcher Vorbeiflug eine seltene Gelegenheit, die Instrumente unter bekannten Bedingungen zu testen.",
         "Для учёных такой пролёт — редкая возможность проверить приборы в известных условиях.",
         {"Für": "для", "Forscher": "учёных", "ist": "есть", "solcher": "такой", "Vorbeiflug": "пролёт",
          "seltene": "редкая", "Gelegenheit": "возможность", "Instrumente": "приборы",
          "unter bekannten Bedingungen": "в известных условиях", "zu testen": "проверить"}),
        ("Im Erdschatten musste Juice allein mit Batteriestrom auskommen.",
         "В тени Земли Juice пришлось обходиться одними аккумуляторами.",
         {"Im": "в", "Erdschatten": "тени Земли", "musste": "пришлось", "allein": "только",
          "mit Batteriestrom": "с питанием от батарей", "auskommen": "обходиться"}),
        ("Außerdem durchquerte die Sonde den Magnetschweif der Erde und maß dort Magnetfelder und geladene Teilchen.",
         "Кроме того, зонд пересёк магнитный хвост Земли и измерил там магнитные поля и заряженные частицы.",
         {"Außerdem": "кроме того", "durchquerte": "пересёк", "Sonde": "зонд",
          "Magnetschweif": "магнитный хвост", "der Erde": "Земли", "maß": "измерил", "dort": "там",
          "Magnetfelder": "магнитные поля", "geladene": "заряженные", "Teilchen": "частицы"}),
    ],
    ('fig', 'path'),
    [
        ("Juice ist seit April 2023 unterwegs.",
         "Juice находится в пути с апреля 2023 года.",
         {"ist+unterwegs": "в пути", "seit": "с", "April": "апреля"}),
        ("Im Januar 2029 soll die Sonde noch einmal an der Erde vorbeifliegen, im Juli 2031 erreicht sie dann den Jupiter.",
         "В январе 2029 года зонд должен ещё раз пролететь мимо Земли, а в июле 2031-го он достигнет Юпитера.",
         {"Im Januar": "в январе", "soll": "должен", "Sonde": "зонд", "noch einmal": "ещё раз",
          "an der Erde": "мимо Земли", "vorbeifliegen": "пролететь мимо", "im Juli": "в июле",
          "erreicht": "достигнет", "dann": "затем", "den Jupiter": "Юпитера"}),
        ("Dort soll sie die Eismonde Ganymed, Kallisto und Europa untersuchen, unter deren Oberfläche Ozeane vermutet werden.",
         "Там ему предстоит изучать ледяные спутники Ганимед, Каллисто и Европу, под поверхностью которых предполагают океаны.",
         {"Dort": "там", "soll": "должен", "Eismonde": "ледяные спутники", "Ganymed": "Ганимед",
          "Kallisto": "Каллисто", "Europa": "Европу", "untersuchen": "изучать", "unter": "под",
          "deren": "которых", "Oberfläche": "поверхностью", "Ozeane": "океаны",
          "vermutet werden": "предполагаются"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  2. Сатурн в противостоянии
# ════════════════════════════════════════════════════════════════════
ARTICLES['saturn-opposition-2026'] = [
    ('fig', 'cassini'),
    [
        ("Am 4. Oktober 2026 stand Saturn in Opposition zur Sonne.",
         "4 октября 2026 года Сатурн оказался в противостоянии с Солнцем.",
         {"Am": "", "Oktober": "октября", "stand": "стоял", "Saturn": "Сатурн",
          "in Opposition": "в противостоянии", "zur Sonne": "с Солнцем"}),
        ("Das bedeutet, dass die Erde genau zwischen der Sonne und dem Ringplaneten steht.",
         "Это значит, что Земля находится точно между Солнцем и окольцованной планетой.",
         {"Das": "это", "bedeutet": "значит", "dass": "что", "Erde": "Земля", "genau": "точно",
          "zwischen": "между", "der Sonne": "Солнцем", "dem Ringplaneten": "окольцованной планетой",
          "steht": "стоит"}),
        ("Saturn geht deshalb bei Sonnenuntergang auf, bei Sonnenaufgang unter und ist die ganze Nacht zu sehen.",
         "Поэтому Сатурн восходит на закате, заходит на рассвете и виден всю ночь.",
         {"Saturn": "Сатурн", "geht+auf": "восходит", "deshalb": "поэтому",
          "bei Sonnenuntergang": "на закате", "bei Sonnenaufgang": "на рассвете", "unter": "заходит",
          "ist+zu sehen": "виден", "die ganze Nacht": "всю ночь"}),
    ],
    ('fig', 'webb'),
    [
        ("In diesen Tagen ist uns Saturn so nah wie sonst im ganzen Jahr nicht.",
         "В эти дни Сатурн ближе к нам, чем в любое другое время года.",
         {"In diesen Tagen": "в эти дни", "ist": "", "uns": "к нам", "Saturn": "Сатурн",
          "so nah": "так близко", "wie": "как", "sonst": "в другое время", "im ganzen Jahr": "за весь год",
          "nicht": "не"}),
        ("Trotzdem trennen uns rund 1,26 Milliarden Kilometer von ihm.",
         "И всё же нас разделяют с ним около 1,26 миллиарда километров.",
         {"Trotzdem": "тем не менее", "trennen": "разделяют", "uns": "нас", "rund": "около",
          "Milliarden": "миллиарда", "Kilometer": "километров", "von ihm": "от него"}),
        ("Das Licht, das Saturn zurückwirft, ist bis zur Erde etwa 70 Minuten unterwegs.",
         "Свет, отражённый Сатурном, идёт до Земли около 70 минут.",
         {"Licht": "свет", "das": "который", "Saturn": "Сатурн", "zurückwirft": "отражает",
          "ist+unterwegs": "в пути", "bis zur Erde": "до Земли", "etwa": "около", "Minuten": "минут"}),
    ],
    [
        ("Mit einer Helligkeit von 0,3 Magnituden ist Saturn mit bloßem Auge leicht zu finden.",
         "При блеске 0,3 звёздной величины Сатурн легко найти невооружённым глазом.",
         {"Mit einer Helligkeit": "при яркости", "von": "в", "Magnituden": "звёздных величин",
          "ist+zu finden": "можно найти", "Saturn": "Сатурн", "mit bloßem Auge": "невооружённым глазом",
          "leicht": "легко"}),
        ("Er steht im Sternbild Walfisch, nahe der Grenze zu den Fischen, und leuchtet dort als hellster Punkt.",
         "Он находится в созвездии Кита, у границы с Рыбами, и светит там самой яркой точкой.",
         {"steht": "стоит", "im Sternbild": "в созвездии", "Walfisch": "Кит", "nahe": "вблизи",
          "der Grenze": "границы", "zu den Fischen": "с Рыбами", "leuchtet": "светит", "dort": "там",
          "als": "как", "hellster": "самая яркая", "Punkt": "точка"}),
        ("Am höchsten steht er gegen Mitternacht über dem Südhorizont.",
         "Выше всего он стоит около полуночи над южным горизонтом.",
         {"Am höchsten": "выше всего", "steht": "стоит", "gegen Mitternacht": "около полуночи",
          "über": "над", "dem Südhorizont": "южным горизонтом"}),
    ],
    [
        ("Wer ein kleines Teleskop besitzt, sollte jetzt unbedingt einen Blick auf die Ringe werfen.",
         "Тому, у кого есть небольшой телескоп, сейчас непременно стоит взглянуть на кольца.",
         {"Wer": "кто", "kleines": "небольшой", "Teleskop": "телескоп", "besitzt": "имеет",
          "sollte": "следует", "jetzt": "сейчас", "unbedingt": "непременно",
          "einen": "", "Blick+werfen": "бросить взгляд", "auf die Ringe": "на кольца"}),
        ("Im Jahr 2025 blickten wir genau auf ihre Kante, deshalb waren sie fast unsichtbar.",
         "В 2025 году мы смотрели точно на их ребро, поэтому они были почти невидимы.",
         {"Im Jahr": "в году", "blickten": "смотрели", "genau": "точно", "auf": "на",
          "ihre Kante": "их ребро", "deshalb": "поэтому", "waren": "были", "fast": "почти",
          "unsichtbar": "невидимы"}),
        ("Jetzt sind sie wieder um etwa sieben Grad geneigt und öffnen sich von Jahr zu Jahr weiter.",
         "Теперь они снова наклонены примерно на семь градусов и год от года раскрываются всё шире.",
         {"Jetzt": "теперь", "sind+geneigt": "наклонены", "wieder": "снова", "um etwa": "примерно на",
          "sieben Grad": "семь градусов", "öffnen sich": "раскрываются",
          "von Jahr zu Jahr": "год от года", "weiter": "дальше"}),
        ("Auch der größte Saturnmond Titan ist in einem kleinen Teleskop als Lichtpunkt neben dem Planeten zu erkennen.",
         "Крупнейший спутник Сатурна Титан тоже виден в небольшой телескоп как светлая точка рядом с планетой.",
         {"Auch": "тоже", "größte": "крупнейший", "Saturnmond": "спутник Сатурна", "Titan": "Титан",
          "ist+zu erkennen": "различим", "in einem kleinen Teleskop": "в небольшой телескоп",
          "als": "как", "Lichtpunkt": "светлая точка", "neben dem Planeten": "рядом с планетой"}),
    ],
    ('fig', 'hubble'),
    [
        ("Wie Saturn aus der Nähe aussieht, zeigen Bilder der beiden großen Weltraumteleskope.",
         "Как Сатурн выглядит вблизи, показывают снимки двух больших космических телескопов.",
         {"Wie": "как", "Saturn": "Сатурн", "aus der Nähe": "вблизи", "aussieht": "выглядит",
          "zeigen": "показывают", "Bilder": "снимки", "der beiden": "обоих", "großen": "больших",
          "Weltraumteleskope": "космических телескопов"}),
        ("Hubble fotografiert ihn im sichtbaren Licht, das James-Webb-Teleskop dagegen im Infrarot.",
         "«Хаббл» снимает его в видимом свете, а телескоп «Джеймс Уэбб» — в инфракрасном.",
         {"Hubble": "Хаббл", "fotografiert": "фотографирует", "ihn": "его",
          "im sichtbaren Licht": "в видимом свете", "James-Webb-Teleskop": "телескоп «Джеймс Уэбб»",
          "dagegen": "напротив", "im Infrarot": "в инфракрасном"}),
        ("Im Infrarot leuchten die eisigen Ringe besonders hell.",
         "В инфракрасном свете ледяные кольца сияют особенно ярко.",
         {"Im Infrarot": "в инфракрасном", "leuchten": "светятся", "eisigen": "ледяные",
          "Ringe": "кольца", "besonders": "особенно", "hell": "ярко"}),
    ],
    [
        ("Die nächste Opposition folgt Mitte Oktober 2027, dann sind die Ringe noch etwas weiter geöffnet.",
         "Следующее противостояние будет в середине октября 2027 года — тогда кольца раскроются ещё немного шире.",
         {"nächste": "следующее", "Opposition": "противостояние", "folgt": "последует",
          "Mitte Oktober": "в середине октября", "dann": "тогда", "sind+geöffnet": "раскрыты",
          "Ringe": "кольца", "noch etwas": "ещё немного", "weiter": "шире"}),
    ],
]

# ════════════════════════════════════════════════════════════════════
#  3. Crew-13 — экипаж на МКС
# ════════════════════════════════════════════════════════════════════
ARTICLES['crew-13-iss-2026'] = [
    ('fig', 'launch'),
    [
        ("Am 1. Oktober 2026 ist die Mission Crew-13 vom Weltraumbahnhof Cape Canaveral in Florida gestartet.",
         "1 октября 2026 года с космодрома на мысе Канаверал во Флориде стартовала миссия Crew-13.",
         {"Am": "", "Oktober": "октября", "ist+gestartet": "стартовала", "Mission": "миссия",
          "vom Weltraumbahnhof": "с космодрома", "Cape Canaveral": "мыс Канаверал",
          "in Florida": "во Флориде"}),
        ("Eine Falcon-9-Rakete von SpaceX hob um 11:10 Uhr Ortszeit ab.",
         "Ракета Falcon 9 компании SpaceX стартовала в 11:10 по местному времени.",
         {"Rakete": "ракета", "von SpaceX": "компании SpaceX", "hob+ab": "взлетела", "um": "в",
          "Uhr": "часов", "Ortszeit": "местного времени"}),
        ("An Bord der Kapsel Crew Dragon »Grace« saßen vier Raumfahrer aus drei Ländern.",
         "На борту капсулы Crew Dragon «Grace» находились четверо космонавтов из трёх стран.",
         {"An Bord": "на борту", "der Kapsel": "капсулы", "saßen": "сидели", "vier": "четыре",
          "Raumfahrer": "космонавта", "aus drei Ländern": "из трёх стран"}),
    ],
    [
        ("Kommandantin ist die NASA-Astronautin Jessica Watkins, eine Geologin, die bereits zum zweiten Mal ins All fliegt.",
         "Командир — астронавт NASA Джессика Уоткинс, геолог, которая летит в космос уже во второй раз.",
         {"Kommandantin": "командир", "ist": "—", "NASA-Astronautin": "астронавт NASA",
          "Geologin": "геолог", "die#2": "которая", "bereits": "уже", "zum zweiten Mal": "во второй раз",
          "ins All": "в космос", "fliegt": "летит"}),
        ("Für Pilot Luke Delaney, den russischen Kosmonauten Sergei Teterjatnikow und den Kanadier Joshua Kutryk ist es der erste Raumflug.",
         "Для пилота Люка Делейни, российского космонавта Сергея Тетерятникова и канадца Джошуа Кутрика это первый космический полёт.",
         {"Für": "для", "Pilot": "пилота", "russischen": "российского", "Kosmonauten": "космонавта",
          "Kanadier": "канадца", "ist es": "это", "erste": "первый", "Raumflug": "космический полёт"}),
    ],
    ('fig', 'crew'),
    [
        ("Schon acht Stunden nach dem Start legte die Kapsel an der Internationalen Raumstation an.",
         "Уже через восемь часов после старта капсула пристыковалась к Международной космической станции.",
         {"Schon": "уже", "acht Stunden": "восемь часов", "nach dem Start": "после старта",
          "legte+an#2": "причалила", "Kapsel": "капсула", "an der": "к",
          "Internationalen Raumstation": "Международной космической станции"}),
        ("Für eine Besatzung der NASA ist das ein Rekord.",
         "Для экипажа NASA это рекорд.",
         {"Für": "для", "Besatzung": "экипажа", "ist das": "это", "Rekord": "рекорд"}),
        ("Die Kopplung erfolgte am Modul Harmony, während die Station über dem Nordostpazifik flog.",
         "Стыковка прошла к модулю Harmony, когда станция пролетала над северо-восточной частью Тихого океана.",
         {"Kopplung": "стыковка", "erfolgte": "произошла", "am Modul": "к модулю", "während": "пока",
          "Station": "станция", "über": "над", "dem Nordostpazifik": "северо-востоком Тихого океана",
          "flog": "летела"}),
    ],
    [
        ("Die vier Raumfahrer bleiben etwa sechs Monate an Bord.",
         "Четверо космонавтов пробудут на борту около шести месяцев.",
         {"vier": "четыре", "Raumfahrer": "космонавта", "bleiben": "останутся", "etwa": "около",
          "sechs Monate": "шесть месяцев", "an Bord": "на борту"}),
        ("Sie sollen die Station warten, mehrere Außeneinsätze absolvieren und Frachtschiffe in Empfang nehmen.",
         "Им предстоит обслуживать станцию, совершить несколько выходов в открытый космос и принимать грузовые корабли.",
         {"sollen": "должны", "Station": "станцию", "warten": "обслуживать", "mehrere": "несколько",
          "Außeneinsätze": "выходов в космос", "absolvieren": "выполнить",
          "Frachtschiffe": "грузовые корабли", "in Empfang nehmen": "принимать"}),
        ("Auf dem Programm stehen außerdem zahlreiche Experimente, etwa mit Stammzellen, die bei der Behandlung von Herzkrankheiten und Parkinson helfen könnten.",
         "В программе также многочисленные эксперименты — например, со стволовыми клетками, которые могли бы помочь в лечении болезней сердца и Паркинсона.",
         {"Auf dem Programm": "в программе", "stehen": "стоят", "außerdem": "кроме того",
          "zahlreiche": "многочисленные", "Experimente": "эксперименты", "etwa": "например",
          "mit Stammzellen": "со стволовыми клетками", "die": "которые",
          "bei der Behandlung": "при лечении", "von Herzkrankheiten": "болезней сердца",
          "Parkinson": "Паркинсона", "helfen": "помочь", "könnten": "могли бы"}),
        ("Andere Versuche beschäftigen sich mit dem Anbau von Pflanzen im All.",
         "Другие опыты посвящены выращиванию растений в космосе.",
         {"Andere": "другие", "Versuche": "опыты", "beschäftigen sich": "занимаются",
          "mit dem Anbau": "выращиванием", "von Pflanzen": "растений", "im All": "в космосе"}),
    ],
    ('fig', 'sunset'),
    [
        ("Für Joshua Kutryk ist die Mission auch privat etwas Besonderes, denn seine Frau erwartet in einigen Wochen das dritte Kind.",
         "Для Джошуа Кутрика миссия особенная и в личном плане: через несколько недель его жена ждёт третьего ребёнка.",
         {"Für": "для", "ist": "", "Mission": "миссия", "auch": "и", "privat": "в личном плане",
          "etwas Besonderes": "нечто особенное", "denn": "ведь", "seine Frau": "его жена",
          "erwartet": "ждёт", "in einigen Wochen": "через несколько недель", "dritte": "третьего",
          "Kind": "ребёнка"}),
        ("Die Geburt wird er also aus dem Weltraum miterleben.",
         "Значит, рождение ребёнка он переживёт из космоса.",
         {"Geburt": "рождение", "wird+miterleben": "переживёт вместе", "also": "значит",
          "aus dem Weltraum": "из космоса"}),
        ("Die bisherige Besatzung Crew-12 soll die Station frühestens am 7. Oktober verlassen.",
         "Предыдущий экипаж Crew-12 должен покинуть станцию не раньше 7 октября.",
         {"bisherige": "прежний", "Besatzung": "экипаж", "soll": "должен", "Station": "станцию",
          "frühestens": "не раньше", "am": "", "Oktober": "октября", "verlassen": "покинуть"}),
    ],
]
