"""
Словарь новостей: словоформа → лемма (W) и лемма → статья (L).

Общие слова build.py берёт из глоссариев книг (data/books/*/glossary.json);
здесь — то, чего в книгах нет, и переопределения там, где книжная лемма
не подходит по смыслу (acht — не «Acht», Grad — не «gerade»).
Формат статьи тот же, что у книг: ru, pos, art/pl у существительных,
forms у глаголов, note — пояснение.
"""

N = 'сущ.'
V = 'гл.'
A = 'прил.'
ADV = 'нареч.'


def n(ru, art, pl, **kw):
    return dict(ru=ru, pos=N, art=art, pl=pl, **kw)


def v(ru, forms, **kw):
    return dict(ru=ru, pos=V, forms=forms, **kw)


def a(ru, **kw):
    return dict(ru=ru, pos=A, **kw)


def adv(ru, **kw):
    return dict(ru=ru, pos=ADV, **kw)


def name(ru, **kw):
    return dict(ru=ru, pos='имя собств.', **kw)


def geo(ru, **kw):
    return dict(ru=ru, pos='геогр.', **kw)


W = {
    # переопределения книжных лемм
    'acht': 'acht', 'all': 'All', 'bekannten': 'bekannt', 'grad': 'Grad',
    'weise': 'Weise', 'warten': 'warten (обслуживать)', 'legte': 'anlegen',
    # Juice
    'europäische': 'europäisch', 'raumsonde': 'Raumsonde', 'september': 'September',
    'erneut': 'erneut', 'vorbeigeflogen': 'vorbeifliegen', 'vorbeifliegen': 'vorbeifliegen',
    'mitteleuropäischer': 'mitteleuropäisch', 'sommerzeit': 'Sommerzeit',
    'planeten': 'Planet', 'kilometer': 'Kilometer', 'indischen': 'indisch', 'ozean': 'Ozean',
    'manöver': 'Manöver', 'sogenannter': 'sogenannt', 'swing-by': 'Swing-by',
    'schwerkraft': 'Schwerkraft', 'lenkte': 'ablenken', 'sonde': 'Sonde', 'schneller': 'schnell',
    'pro': 'pro', 'sekunde': 'Sekunde', 'spart': 'sparen', 'mission': 'Mission',
    'wertvollen': 'wertvoll', 'treibstoff': 'Treibstoff', 'vorbeiflug': 'Vorbeiflug',
    'vorbeiflugs': 'Vorbeiflug', 'erforderte': 'erfordern', 'hochpräzise': 'hochpräzise',
    'navigation': 'Navigation', 'echtzeit': 'Echtzeit', 'angela': 'Angela', 'dietz': 'Dietz',
    'esa': 'ESA', 'betrieb': 'Betrieb', 'verantwortlich': 'verantwortlich',
    'geplanten': 'planen', 'kurskorrekturen': 'Kurskorrektur', 'schalteten': 'einschalten',
    'ingenieure': 'Ingenieur', 'kameras': 'Kamera', 'messinstrumente': 'Messinstrument',
    'überwachungskamera': 'Überwachungskamera', 'fotografierte': 'fotografieren',
    'fotografiert': 'fotografieren', 'afrika': 'Afrika', 'madagaskar': 'Madagaskar',
    'bildes': 'Bild', 'bilder': 'Bild', 'winziger': 'winzig', 'grauer': 'grau', 'punkt': 'Punkt',
    'navigationskamera': 'Navigationskamera', 'größten': 'groß', 'annäherung': 'Annäherung',
    'schmale': 'schmal', 'sichel': 'Sichel', 'forscher': 'Forscher', 'solcher': 'solch',
    'seltene': 'selten', 'instrumente': 'Instrument', 'bedingungen': 'Bedingung',
    'testen': 'testen', 'erdschatten': 'Erdschatten', 'juice': 'Juice',
    'batteriestrom': 'Batteriestrom', 'auskommen': 'auskommen', 'außerdem': 'außerdem',
    'durchquerte': 'durchqueren', 'magnetschweif': 'Magnetschweif', 'maß': 'messen',
    'magnetfelder': 'Magnetfeld', 'geladene': 'geladen', 'teilchen': 'Teilchen',
    'seit': 'seit', 'april': 'April', 'unterwegs': 'unterwegs', 'januar': 'Januar',
    'juli': 'Juli', 'erreicht': 'erreichen', 'jupiter': 'Jupiter', 'eismonde': 'Eismond',
    'ganymed': 'Ganymed', 'kallisto': 'Kallisto', 'europa': 'Europa', 'ozeane': 'Ozean',
    'vermutet': 'vermuten',
    # Сатурн
    'oktober': 'Oktober', 'saturn': 'Saturn', 'opposition': 'Opposition',
    'bedeutet': 'bedeuten', 'ringplaneten': 'Ringplanet', 'deshalb': 'deshalb',
    'sonnenuntergang': 'Sonnenuntergang', 'sonnenaufgang': 'Sonnenaufgang', 'nah': 'nah',
    'trotzdem': 'trotzdem', 'trennen': 'trennen', 'milliarden': 'Milliarde',
    'zurückwirft': 'zurückwerfen', 'minuten': 'Minute', 'helligkeit': 'Helligkeit',
    'magnituden': 'Magnitude', 'bloßem': 'bloß', 'finden': 'finden', 'sternbild': 'Sternbild',
    'walfisch': 'Walfisch', 'nahe': 'nahe', 'grenze': 'Grenze', 'fischen': 'Fische',
    'leuchtet': 'leuchten', 'leuchten': 'leuchten', 'hellster': 'hell', 'höchsten': 'hoch',
    'südhorizont': 'Südhorizont', 'teleskop': 'Teleskop', 'besitzt': 'besitzen',
    'unbedingt': 'unbedingt', 'kante': 'Kante', 'sieben': 'sieben', 'öffnen': 'öffnen',
    'geöffnet': 'öffnen', 'saturnmond': 'Saturnmond', 'titan': 'Titan',
    'lichtpunkt': 'Lichtpunkt', 'aussieht': 'aussehen', 'weltraumteleskope': 'Weltraumteleskop',
    'hubble': 'Hubble', 'sichtbaren': 'sichtbar', 'james-webb-teleskop': 'James-Webb-Teleskop',
    'infrarot': 'Infrarot', 'eisigen': 'eisig', 'nächste': 'nächste',
    'planeten#saturn': 'Planet',
    # Crew-13
    'mission#crew': 'Mission', 'crew': 'Crew', 'weltraumbahnhof': 'Weltraumbahnhof',
    'cape': 'Cape Canaveral', 'canaveral': 'Cape Canaveral', 'florida': 'Florida',
    'gestartet': 'starten', 'falcon': 'Falcon', 'rakete': 'Rakete', 'spacex': 'SpaceX',
    'hob': 'abheben', 'ortszeit': 'Ortszeit', 'bord': 'Bord', 'kapsel': 'Kapsel',
    'dragon': 'Dragon', 'grace': 'Grace', 'raumfahrer': 'Raumfahrer', 'ländern': 'Land',
    'kommandantin': 'Kommandantin', 'nasa-astronautin': 'Astronautin', 'jessica': 'Jessica',
    'watkins': 'Watkins', 'geologin': 'Geologin', 'zweiten': 'zweite', 'pilot': 'Pilot',
    'luke': 'Luke', 'delaney': 'Delaney', 'russischen': 'russisch', 'kosmonauten': 'Kosmonaut',
    'sergei': 'Sergei', 'teterjatnikow': 'Teterjatnikow', 'kanadier': 'Kanadier',
    'joshua': 'Joshua', 'kutryk': 'Kutryk', 'raumflug': 'Raumflug', 'start': 'Start',
    'internationalen': 'international', 'raumstation': 'Raumstation', 'besatzung': 'Besatzung',
    'nasa': 'NASA', 'rekord': 'Rekord', 'kopplung': 'Kopplung', 'erfolgte': 'erfolgen',
    'modul': 'Modul', 'harmony': 'Harmony', 'station': 'Station',
    'nordostpazifik': 'Nordostpazifik', 'außeneinsätze': 'Außeneinsatz',
    'absolvieren': 'absolvieren', 'frachtschiffe': 'Frachtschiff', 'empfang': 'Empfang',
    'programm': 'Programm', 'zahlreiche': 'zahlreich', 'experimente': 'Experiment',
    'stammzellen': 'Stammzelle', 'behandlung': 'Behandlung', 'herzkrankheiten': 'Herzkrankheit',
    'parkinson': 'Parkinson', 'beschäftigen': 'sich beschäftigen', 'anbau': 'Anbau',
    'pflanzen': 'Pflanze', 'privat': 'privat', 'besonderes': 'Besondere', 'einigen': 'einige',
    'geburt': 'Geburt', 'miterleben': 'miterleben', 'weltraum': 'Weltraum',
    'bisherige': 'bisherig', 'frühestens': 'frühestens',
}
# служебные ключи с «#» — только для читаемости, в словарь не идут
W = {k: v for k, v in W.items() if '#' not in k}

L = {
    'acht': dict(ru='восемь', pos='числ.'),
    'All': n('космос, вселенная', 'das', None, note='ins All fliegen — лететь в космос; im All — в космосе'),
    'bekannt': a('известный, знакомый'),
    'Grad': n('градус', 'der', 'die Grade', note='после числа мн. ч. не ставится: 20 Grad'),
    'Weise': n('способ, манера', 'die', 'die Weisen', note='auf diese Weise — таким образом'),
    'warten (обслуживать)': v('обслуживать, проводить техобслуживание', 'wartete · hat gewartet',
                              note='омоним: warten auf — «ждать»; здесь — обслуживать технику'),
    'anlegen': v('причаливать, пристыковываться', 'legte an · hat angelegt',
                 note='legen + отделяемая приставка an: die Kapsel legte an der Station an'),
    'europäisch': a('европейский'),
    'Raumsonde': n('космический зонд', 'die', 'die Raumsonden'),
    'September': n('сентябрь', 'der', 'die September'),
    'erneut': adv('снова, повторно'),
    'vorbeifliegen': v('пролетать мимо', 'flog vorbei · ist vorbeigeflogen',
                       note='an etwas (D) vorbeifliegen — пролететь мимо чего-то'),
    'mitteleuropäisch': a('центральноевропейский', note='mitteleuropäische Sommerzeit (MESZ) — летнее время Центральной Европы'),
    'Sommerzeit': n('летнее время', 'die', None),
    'Planet': n('планета', 'der', 'die Planeten', note='слабое склонение: den/dem/des Planeten'),
    'Kilometer': n('километр', 'der', 'die Kilometer'),
    'indisch': a('индийский', note='der Indische Ozean — Индийский океан'),
    'Ozean': n('океан', 'der', 'die Ozeane'),
    'Manöver': n('манёвр', 'das', 'die Manöver'),
    'sogenannt': a('так называемый'),
    'Swing-by': n('гравитационный манёвр', 'der', 'die Swing-bys', note='англицизм; по-немецки также Gravitationsmanöver'),
    'Schwerkraft': n('сила тяжести, притяжение', 'die', None),
    'ablenken': v('отклонять', 'lenkte ab · hat abgelenkt'),
    'Sonde': n('зонд', 'die', 'die Sonden'),
    'schnell': a('быстрый', forms='schnell · schneller · am schnellsten'),
    'pro': dict(ru='в, за (на единицу)', pos='предл.', note='3,5 Kilometer pro Sekunde — 3,5 км в секунду'),
    'Sekunde': n('секунда', 'die', 'die Sekunden'),
    'sparen': v('экономить, копить', 'sparte · hat gespart'),
    'Mission': n('миссия', 'die', 'die Missionen'),
    'wertvoll': a('ценный, драгоценный'),
    'Treibstoff': n('топливо', 'der', 'die Treibstoffe'),
    'Vorbeiflug': n('пролёт мимо', 'der', 'die Vorbeiflüge'),
    'erfordern': v('требовать', 'erforderte · hat erfordert'),
    'hochpräzise': a('сверхточный'),
    'Navigation': n('навигация', 'die', None),
    'Echtzeit': n('реальное время', 'die', None, note='in Echtzeit — в реальном времени'),
    'Angela': name('Ангела (имя)'),
    'Dietz': name('Диц (фамилия)'),
    'ESA': dict(ru='ЕКА, Европейское космическое агентство', pos='сокр.', note='die ESA = European Space Agency'),
    'Betrieb': n('работа, эксплуатация', 'der', 'die Betriebe', note='также «предприятие»'),
    'verantwortlich': a('ответственный', note='für etwas verantwortlich sein — отвечать за что-то'),
    'planen': v('планировать', 'plante · hat geplant'),
    'Kurskorrektur': n('коррекция курса', 'die', 'die Kurskorrekturen'),
    'einschalten': v('включать', 'schaltete ein · hat eingeschaltet'),
    'Ingenieur': n('инженер', 'der', 'die Ingenieure'),
    'Kamera': n('камера', 'die', 'die Kameras'),
    'Messinstrument': n('измерительный прибор', 'das', 'die Messinstrumente'),
    'Überwachungskamera': n('камера наблюдения', 'die', 'die Überwachungskameras'),
    'fotografieren': v('фотографировать', 'fotografierte · hat fotografiert'),
    'Afrika': geo('Африка'),
    'Madagaskar': geo('Мадагаскар'),
    'Bild': n('картина, снимок', 'das', 'die Bilder'),
    'winzig': a('крошечный'),
    'grau': a('серый'),
    'Punkt': n('точка', 'der', 'die Punkte'),
    'Navigationskamera': n('навигационная камера', 'die', 'die Navigationskameras'),
    'groß': a('большой', forms='groß · größer · am größten'),
    'Annäherung': n('сближение', 'die', 'die Annäherungen'),
    'schmal': a('узкий'),
    'Sichel': n('серп', 'die', 'die Sicheln'),
    'Forscher': n('исследователь, учёный', 'der', 'die Forscher'),
    'solch': dict(ru='такой', pos='мест.', note='ein solcher Vorbeiflug — такой пролёт'),
    'selten': a('редкий'),
    'Instrument': n('прибор, инструмент', 'das', 'die Instrumente'),
    'Bedingung': n('условие', 'die', 'die Bedingungen'),
    'testen': v('испытывать, проверять', 'testete · hat getestet'),
    'Erdschatten': n('тень Земли', 'der', None),
    'Juice': name('Juice (зонд ЕКА)', note='JUpiter ICy moons Explorer — исследователь ледяных лун Юпитера'),
    'Batteriestrom': n('питание от аккумулятора', 'der', None),
    'auskommen': v('обходиться', 'kam aus · ist ausgekommen', note='mit etwas auskommen — обходиться чем-то'),
    'außerdem': adv('кроме того'),
    'durchqueren': v('пересекать', 'durchquerte · hat durchquert'),
    'Magnetschweif': n('магнитный хвост', 'der', 'die Magnetschweife'),
    'messen': v('измерять', 'maß · hat gemessen'),
    'Magnetfeld': n('магнитное поле', 'das', 'die Magnetfelder'),
    'geladen': a('заряженный'),
    'Teilchen': n('частица', 'das', 'die Teilchen'),
    'seit': dict(ru='с (какого-то времени)', pos='предл.'),
    'April': n('апрель', 'der', 'die Aprile'),
    'unterwegs': adv('в пути'),
    'Januar': n('январь', 'der', 'die Januare'),
    'Juli': n('июль', 'der', 'die Julis'),
    'erreichen': v('достигать', 'erreichte · hat erreicht'),
    'Jupiter': name('Юпитер', note='с артиклем: der Jupiter'),
    'Eismond': n('ледяной спутник', 'der', 'die Eismonde'),
    'Ganymed': name('Ганимед (спутник Юпитера)'),
    'Kallisto': name('Каллисто (спутник Юпитера)'),
    'Europa': name('Европа (спутник Юпитера; также континент)'),
    'vermuten': v('предполагать', 'vermutete · hat vermutet'),
    'Oktober': n('октябрь', 'der', 'die Oktober'),
    'Saturn': name('Сатурн'),
    'Opposition': n('противостояние (в астрономии); оппозиция', 'die', 'die Oppositionen'),
    'bedeuten': v('означать', 'bedeutete · hat bedeutet'),
    'Ringplanet': n('планета с кольцами', 'der', 'die Ringplaneten'),
    'deshalb': adv('поэтому'),
    'Sonnenuntergang': n('закат', 'der', 'die Sonnenuntergänge'),
    'Sonnenaufgang': n('восход солнца', 'der', 'die Sonnenaufgänge'),
    'nah': a('близкий', forms='nah · näher · am nächsten'),
    'trotzdem': adv('тем не менее, всё же'),
    'trennen': v('разделять', 'trennte · hat getrennt'),
    'Milliarde': n('миллиард', 'die', 'die Milliarden'),
    'zurückwerfen': v('отражать, отбрасывать', 'warf zurück · hat zurückgeworfen'),
    'Minute': n('минута', 'die', 'die Minuten'),
    'Helligkeit': n('яркость, блеск', 'die', 'die Helligkeiten'),
    'Magnitude': n('звёздная величина', 'die', 'die Magnituden'),
    'bloß': a('голый; простой', note='mit bloßem Auge — невооружённым глазом'),
    'finden': v('находить', 'fand · hat gefunden'),
    'Sternbild': n('созвездие', 'das', 'die Sternbilder'),
    'Walfisch': n('кит; созвездие Кита', 'der', 'die Walfische'),
    'nahe': dict(ru='вблизи, около', pos='предл.'),
    'Grenze': n('граница', 'die', 'die Grenzen'),
    'Fische': n('Рыбы (созвездие)', 'die', None, note='мн. ч. от der Fisch «рыба»'),
    'leuchten': v('светить, сиять', 'leuchtete · hat geleuchtet'),
    'hoch': a('высокий', forms='hoch · höher · am höchsten'),
    'Südhorizont': n('южный горизонт', 'der', None),
    'Teleskop': n('телескоп', 'das', 'die Teleskope'),
    'besitzen': v('владеть, иметь', 'besaß · hat besessen'),
    'unbedingt': adv('непременно, обязательно'),
    'Kante': n('край, ребро', 'die', 'die Kanten'),
    'sieben': dict(ru='семь', pos='числ.'),
    'öffnen': v('открывать', 'öffnete · hat geöffnet', note='sich öffnen — открываться, раскрываться'),
    'Saturnmond': n('спутник Сатурна', 'der', 'die Saturnmonde'),
    'Titan': name('Титан (спутник Сатурна)'),
    'Lichtpunkt': n('светлая точка', 'der', 'die Lichtpunkte'),
    'aussehen': v('выглядеть', 'sah aus · hat ausgesehen'),
    'Weltraumteleskop': n('космический телескоп', 'das', 'die Weltraumteleskope'),
    'Hubble': name('«Хаббл» (космический телескоп)'),
    'sichtbar': a('видимый'),
    'James-Webb-Teleskop': n('телескоп «Джеймс Уэбб»', 'das', None),
    'Infrarot': n('инфракрасный свет', 'das', None, note='im Infrarot — в инфракрасном диапазоне'),
    'eisig': a('ледяной'),
    'nächste': a('следующий; ближайший'),
    'Crew': n('экипаж (англицизм)', 'die', 'die Crews'),
    'Weltraumbahnhof': n('космодром', 'der', 'die Weltraumbahnhöfe'),
    'Cape Canaveral': geo('мыс Канаверал (Флорида)'),
    'Florida': geo('Флорида'),
    'starten': v('стартовать, запускать', 'startete · ist/hat gestartet'),
    'Falcon': name('Falcon (ракета SpaceX)'),
    'Rakete': n('ракета', 'die', 'die Raketen'),
    'SpaceX': name('SpaceX (компания)'),
    'abheben': v('взлетать, отрываться от земли', 'hob ab · ist abgehoben'),
    'Ortszeit': n('местное время', 'die', None),
    'Bord': n('борт', 'der', None, note='an Bord — на борту'),
    'Kapsel': n('капсула', 'die', 'die Kapseln'),
    'Dragon': name('Dragon (корабль SpaceX)'),
    'Grace': name('Grace (имя капсулы)'),
    'Raumfahrer': n('космонавт', 'der', 'die Raumfahrer'),
    'Land': n('страна; суша; деревня', 'das', 'die Länder'),
    'Kommandantin': n('командир (о женщине)', 'die', 'die Kommandantinnen'),
    'Astronautin': n('астронавт (о женщине)', 'die', 'die Astronautinnen'),
    'Jessica': name('Джессика (имя)'),
    'Watkins': name('Уоткинс (фамилия)'),
    'Geologin': n('геолог (о женщине)', 'die', 'die Geologinnen'),
    'zweite': dict(ru='второй', pos='числ.', note='zum zweiten Mal — во второй раз'),
    'Pilot': n('пилот', 'der', 'die Piloten'),
    'Luke': name('Люк (имя)'),
    'Delaney': name('Делейни (фамилия)'),
    'russisch': a('русский; российский'),
    'Kosmonaut': n('космонавт', 'der', 'die Kosmonauten', note='слабое склонение: den Kosmonauten'),
    'Sergei': name('Сергей (имя)'),
    'Teterjatnikow': name('Тетерятников (фамилия)'),
    'Kanadier': n('канадец', 'der', 'die Kanadier'),
    'Joshua': name('Джошуа (имя)'),
    'Kutryk': name('Кутрик (фамилия)'),
    'Raumflug': n('космический полёт', 'der', 'die Raumflüge'),
    'Start': n('старт, запуск', 'der', 'die Starts'),
    'international': a('международный'),
    'Raumstation': n('космическая станция', 'die', 'die Raumstationen'),
    'Besatzung': n('экипаж', 'die', 'die Besatzungen'),
    'NASA': dict(ru='НАСА, космическое агентство США', pos='сокр.'),
    'Rekord': n('рекорд', 'der', 'die Rekorde'),
    'Kopplung': n('стыковка', 'die', 'die Kopplungen'),
    'erfolgen': v('происходить, состояться', 'erfolgte · ist erfolgt'),
    'Modul': n('модуль', 'das', 'die Module'),
    'Harmony': name('Harmony (модуль МКС)'),
    'Station': n('станция', 'die', 'die Stationen'),
    'Nordostpazifik': n('северо-восток Тихого океана', 'der', None),
    'Außeneinsatz': n('выход в открытый космос', 'der', 'die Außeneinsätze'),
    'absolvieren': v('выполнять, проходить', 'absolvierte · hat absolviert'),
    'Frachtschiff': n('грузовой корабль', 'das', 'die Frachtschiffe'),
    'Empfang': n('приём', 'der', 'die Empfänge', note='in Empfang nehmen — принимать'),
    'Programm': n('программа', 'das', 'die Programme'),
    'zahlreich': a('многочисленный'),
    'Experiment': n('эксперимент', 'das', 'die Experimente'),
    'Stammzelle': n('стволовая клетка', 'die', 'die Stammzellen'),
    'Behandlung': n('лечение', 'die', 'die Behandlungen'),
    'Herzkrankheit': n('болезнь сердца', 'die', 'die Herzkrankheiten'),
    'Parkinson': n('болезнь Паркинсона', 'der', None),
    'sich beschäftigen': v('заниматься', 'beschäftigte sich · hat sich beschäftigt',
                           note='sich mit etwas beschäftigen — заниматься чем-то'),
    'Anbau': n('выращивание', 'der', None),
    'Pflanze': n('растение', 'die', 'die Pflanzen'),
    'privat': a('частный, личный'),
    'Besondere': dict(ru='особенное', pos='субст. прил.', decl='das Besondere / etwas Besonderes',
                      note='etwas Besonderes — нечто особенное'),
    'einige': dict(ru='несколько, некоторые', pos='мест.'),
    'Geburt': n('рождение, роды', 'die', 'die Geburten'),
    'miterleben': v('пережить вместе, стать свидетелем', 'erlebte mit · hat miterlebt'),
    'Weltraum': n('космос', 'der', None),
    'bisherig': a('прежний, нынешний (до сих пор)'),
    'frühestens': adv('не раньше, самое раннее'),
}

# Книжные статьи, которым в новостях нужно другое или дополнительное значение
L.update({
    'Erde': n('Земля (планета); земля, почва', 'die', None),
    'Versuch': n('опыт, эксперимент; попытка', 'der', 'die Versuche'),
    'aufnehmen': v('снимать (на камеру); принимать', 'nahm auf · hat aufgenommen'),
    'untersuchen': v('исследовать, изучать', 'untersuchte · hat untersucht'),
    'Frau': n('жена; женщина', 'die', 'die Frauen'),
    'Mond': n('Луна; спутник планеты', 'der', 'die Monde'),
    'neigen': v('наклонять(ся)', 'neigte · hat geneigt', note='geneigt sein — быть наклонённым'),
    'gegen': dict(ru='против; около (о времени)', pos='предл.', note='gegen Mitternacht — около полуночи'),
})
